from flask import Flask, render_template, session
import random

app = Flask(__name__)
app.secret_key = "secretkey"

# -------------------------------------------
# git add .
# git commit -m "Test1"
# git push origin master
# ------------------------------------------


Pohja = 5
Finaali = 5
Top10 = 7
Top3 = 9
Suosikki = 6
Suosikkitop = 4
Extra = 9


songs = [
("Wasted Love \nMaa: Austria\nVuosi: 2025 \nSija: Top3, 1", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=onOex2WXjbA&list=RDonOex2WXjbA&start_radio=1"),
("New Day Will Rise \nMaa: Israel\nVuosi: 2025 \nSija: Top3, 2", Pohja + Top3, "https://www.youtube.com/watch?v=_7zHp51j2WM&list=RD_7zHp51j2WM&start_radio=1"),
("Espresso Macchiato \nMaa: Estonia\nVuosi: 2025 \nSija: Top3, 3", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=F3wsy8bywXQ&list=RDF3wsy8bywXQ&start_radio=1"),
("Code \nMaa: Switzerland\nVuosi: 2024 \nSija: Top3, 1", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=CO_qJf-nW0k&list=RDCO_qJf-nW0k&start_radio=1"),
("Rim Tim Tagi Dim \nMaa: Croatia\nVuosi: 2024 \nSija: Top3, 2", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=YIBjarAiAVc&list=RDYIBjarAiAVc&start_radio=1"),
("Teresa & Maria \nMaa: Ukraine\nVuosi: 2024 \nSija: Top3, 3", Pohja + Top3, "https://www.youtube.com/watch?v=d4N82wPpdg8&list=RDd4N82wPpdg8&start_radio=1"),
("Tattoo \nMaa: Sweden\nVuosi: 2023 \nSija: Top3, 1", Pohja + Top3, "https://www.youtube.com/watch?v=BE2Fj0W4jP4&list=RDBE2Fj0W4jP4&start_radio=1"),
("Cha Cha Cha \nMaa: Finland\nVuosi: 2023 \nSija: Top3, 2", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=l6rS8Dv5g-8&list=RDl6rS8Dv5g-8&start_radio=1"),
("Unicorn \nMaa: Israel\nVuosi: 2023 \nSija: Top3, 3", Pohja + Top3, "https://www.youtube.com/watch?v=Z3mIcCllJXY&list=RDZ3mIcCllJXY&start_radio=1"),
("Stefania \nMaa: Ukraine\nVuosi: 2022 \nSija: Top3, 1", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=F1fl60ypdLs&list=RDF1fl60ypdLs&start_radio=1"),
("Space Man \nMaa: United Kingdom\nVuosi: 2022 \nSija: Top3, 2", Pohja + Top3, "https://www.youtube.com/watch?v=RZ0hqX_92zI&list=RDRZ0hqX_92zI&start_radio=1"),
("SloMo \nMaa: Spain\nVuosi: 2022 \nSija: Top3, 3", Pohja + Top3, "https://www.youtube.com/watch?v=jSQYTt4xg3I&list=RDjSQYTt4xg3I&start_radio=1"),
("Zitti e buoni \nMaa: Italy\nVuosi: 2021 \nSija: Top3, 1", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=RVH5dn1cxAQ&list=RDRVH5dn1cxAQ&start_radio=1"),
("Voilà \nMaa: France\nVuosi: 2021 \nSija: Top3, 2", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=3kiyXRhIXWU&list=RD3kiyXRhIXWU&start_radio=1"),
("Tout l'univers \nMaa: Switzerland\nVuosi: 2021 \nSija: Top3, 3", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=jznH_fltcYA&list=RDjznH_fltcYA&start_radio=1"),
("Arcade \nMaa: Netherlands\nVuosi: 2019 \nSija: Top3, 1", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=R3D-r4ogr7s&list=RDR3D-r4ogr7s&start_radio=1"),
("Soldi \nMaa: Italy\nVuosi: 2019 \nSija: Top3, 2", Pohja + Top3, "https://www.youtube.com/watch?v=M-aoyPa41Ic&list=RDM-aoyPa41Ic&start_radio=1"),
("Scream \nMaa: Russia\nVuosi: 2019 \nSija: Top3, 3", Pohja + Top3, "https://www.youtube.com/watch?v=eNzlxEZ_JG4&list=RDeNzlxEZ_JG4&start_radio=1"),
("Toy \nMaa: Israel\nVuosi: 2018 \nSija: Top3, 1", Pohja + Top3, "https://www.youtube.com/watch?v=84LBjXaeKk4&list=RD84LBjXaeKk4&start_radio=1"),
("Fuego \nMaa: Cyprus\nVuosi: 2018 \nSija: Top3, 2", Pohja + Top3, "https://www.youtube.com/watch?v=vyDTbJ4wenY&list=RDvyDTbJ4wenY&start_radio=1"),
("Nobody but You \nMaa: Austria\nVuosi: 2018 \nSija: Top3, 3", Pohja + Top3, "https://www.youtube.com/watch?v=a8Yvzo1puoE&list=RDa8Yvzo1puoE&start_radio=1"),
("Amar pelos dois \nMaa: Portugal\nVuosi: 2017 \nSija: Top3, 1", Pohja + Top3, "https://www.youtube.com/watch?v=Qotooj7ODCM&list=RDQotooj7ODCM&start_radio=1"),
("Beautiful Mess \nMaa: Bulgaria\nVuosi: 2017 \nSija: Top3, 2", Pohja + Top3, "https://www.youtube.com/watch?v=OMmm-G078LM&list=RDOMmm-G078LM&start_radio=1"),
("Hey Mamma \nMaa: Moldova\nVuosi: 2017 \nSija: Top3", Pohja + Top3, "https://www.youtube.com/watch?v=SWaQdHoCvYk&list=RDSWaQdHoCvYk&start_radio=1"),
("1944 \nMaa: Ukraine\nVuosi: 2016 \nSija: Top3, 1", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=B-rnM-MwRHY&list=RDB-rnM-MwRHY&start_radio=1"),
("Sound of Silence \nMaa: Australia\nVuosi: 2016 \nSija: Top3, 2", Pohja + Top3, "https://www.youtube.com/watch?v=5ymFX91HwM0&list=RD5ymFX91HwM0&start_radio=1"),
("You Are the Only One \nMaa: Russia\nVuosi: 2016 \nSija: Top3, 3", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=e94dst20C9Y&list=RDe94dst20C9Y&start_radio=1"),
("Heroes \nMaa: Sweden\nVuosi: 2015 \nSija: Top3, 1", Pohja + Top3, "https://www.youtube.com/watch?v=5sGOwFVUU0I&list=RD5sGOwFVUU0I&start_radio=1"),
("A Million Voices \nMaa: Russia\nVuosi: 2015 \nSija: Top3, 2", Pohja + Top3, "https://www.youtube.com/watch?v=Q2gbKglCL5s&list=RDQ2gbKglCL5s&start_radio=1"),
("Grande amore \nMaa: Italy\nVuosi: 2015 \nSija: Top3, 3", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=1TOMqZV2jA8&list=RD1TOMqZV2jA8&start_radio=1"),
("Rise Like a Phoenix \nMaa: Austria\nVuosi: 2014 \nSija: Top3, 1", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=SaolVEJEjV4&list=RDSaolVEJEjV4&start_radio=1"),
("Calm After the Storm \nMaa: Netherlands\nVuosi: 2014 \nSija: Top3, 2", Pohja + Top3, "https://www.youtube.com/watch?v=bWe8PRsW4T0&list=RDbWe8PRsW4T0&start_radio=1"),
("Undo \nMaa: Sweden\nVuosi: 2014 \nSija: Top3, 3", Pohja + Top3, "https://www.youtube.com/watch?v=5PQJI-3LW-8&list=RD5PQJI-3LW-8&start_radio=1"),
("Only Teardrops \nMaa: Denmark\nVuosi: 2013 \nSija: Top3, 1", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=k59E7T0H-Us&list=RDk59E7T0H-Us&start_radio=1"),
("Hold Me \nMaa: Azerbaijan\nVuosi: 2013 \nSija: Top3, 2", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=iN3d_V7KVLE&list=RDiN3d_V7KVLE&start_radio=1"),
("Gravity \nMaa: Ukraine\nVuosi: 2013 \nSija: Top3, 3", Pohja + Top3, "https://www.youtube.com/watch?v=Eo5H62mCIsg&list=RDEo5H62mCIsg&start_radio=1"),
("Euphoria \nMaa: Sweden\nVuosi: 2012 \nSija: Top3, 1", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=Pfo-8z86x80&list=RDPfo-8z86x80&start_radio=1"),
("Party for Everybody \nMaa: Russia\nVuosi: 2012 \nSija: Top3, 2", Pohja + Top3, "https://www.youtube.com/watch?v=BgUstrmJzyc&list=RDBgUstrmJzyc&start_radio=1"),
("Nije ljubav stvar \nMaa: Serbia\nVuosi: 2012 \nSija: Top3, 3", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=R9x9VbJzaDQ&list=RDR9x9VbJzaDQ&start_radio=1"),
("Running Scared \nMaa: Azerbaijan\nVuosi: 2011 \nSija: Top3, 1", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=_0tlQUW5X0U&list=RD_0tlQUW5X0U&start_radio=1"),
("Madness of Love \nMaa: Italy\nVuosi: 2011 \nSija: Top3, 2", Pohja + Top3, "https://www.youtube.com/watch?v=TE0uNLp3LuU&list=RDTE0uNLp3LuU&start_radio=1"),
("Popular \nMaa: Sweden\nVuosi: 2011 \nSija: Top3, 3", Pohja + Top3, "https://www.youtube.com/watch?v=-04pUETT7oI&list=RD-04pUETT7oI&start_radio=1"),
("Satellite \nMaa: Germany\nVuosi: 2010 \nSija: Top3, 1", Pohja + Top3, "https://www.youtube.com/watch?v=7pL9vdpSvnY&list=RD7pL9vdpSvnY&start_radio=1"),
("We Could Be the Same \nMaa: Turkey\nVuosi: 2010 \nSija: Top3, 2", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=HB_GnnhNz-8&list=RDHB_GnnhNz-8&start_radio=1"),
("Playing with Fire \nMaa: Romania\nVuosi: 2010 \nSija: Top3, 3", Pohja + Top3 + Suosikkitop, "https://www.youtube.com/watch?v=J9EtMZXeQZw&list=RDJ9EtMZXeQZw&start_radio=1"),
("Fairytale \nMaa: Norway\nVuosi: 2009 \nSija: Top3, 1", Pohja + Top3, "https://www.youtube.com/watch?v=WXwgZL4zx9o&list=RDWXwgZL4zx9o&start_radio=1"),
("Believe \nMaa: Russia\nVuosi: 2008 \nSija: Top3, 1", Pohja + Top3, "https://www.youtube.com/watch?v=-72s4WzUcKI&list=RD-72s4WzUcKI&start_radio=1"),
("Molitva \nMaa: Serbia\nVuosi: 2007 \nSija: Top3, 1", Pohja + Top3, "https://www.youtube.com/watch?v=FSueQN1QvV4&list=RDFSueQN1QvV4&start_radio=1"),
("Dancing Lasha Tumbai \nMaa: Ukraine\nVuosi: 2007 \nSija: Top3, 2", Pohja + Top3, "https://www.youtube.com/watch?v=hfjHJneVonE&list=RDhfjHJneVonE&start_radio=1"),
("Hard Rock Hallelujah \nMaa: Finland\nVuosi: 2006 \nSija: Top3, 1", Pohja + Top3, "https://www.youtube.com/watch?v=gAh9NRGNhUU&list=RDgAh9NRGNhUU&start_radio=1"),

("Bara Bada Bastu \nMaa: Sweden\nVuosi: 2025 \nSija: Top10, 4", Pohja + Top10, "https://www.youtube.com/watch?v=WSh7U3m9KgA&list=RDWSh7U3m9KgA&start_radio=1"),
("Volevo essere un duro \nMaa: Italy\nVuosi: 2025 \nSija: Top10, 5", Pohja + Top10, "https://www.youtube.com/watch?v=Vlu5XXDwHos&list=RDVlu5XXDwHos&start_radio=1"),
("Asteromáta \nMaa: Greece\nVuosi: 2025 \nSija: Top10, 6", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=1qbWRl6h6to&list=RD1qbWRl6h6to&start_radio=1"),
("Maman \nMaa: France\nVuosi: 2025 \nSija: Top10, 7", Pohja + Top10, "https://www.youtube.com/watch?v=jhqJY0ll1Wo&list=RDjhqJY0ll1Wo&start_radio=1"),
("Zjerm \nMaa: Albania\nVuosi: 2025 \nSija: Top10, 8", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=xfn6ssOf_zU&list=RDxfn6ssOf_zU&start_radio=1"),
("Bird Of Pray \nMaa: Ukraine\nVuosi: 2025 \nSija: Top10, 9", Pohja + Top10, "https://www.youtube.com/watch?v=-DG0l8sSNJM&list=RD-DG0l8sSNJM&start_radio=1"),
("Voyage \nMaa: Switzerland\nVuosi: 2025 \nSija: Top10, 10", Pohja + Top10, "https://www.youtube.com/watch?v=5TMc6HzimQo&list=RD5TMc6HzimQo&start_radio=1"),
("Mon amour \nMaa: France\nVuosi: 2024 \nSija: Top10, 4", Pohja + Top10, "https://www.youtube.com/watch?v=-XyLecY2JyE&list=RD-XyLecY2JyE&start_radio=1"),
("Hurricane \nMaa: Israel\nVuosi: 2024 \nSija: Top10, 5", Pohja + Top10, "https://www.youtube.com/watch?v=K60BWlEhtAA&list=RDK60BWlEhtAA&start_radio=1"),
("Doomsday Blue \nMaa: Ireland\nVuosi: 2024 \nSija: Top10, 6", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=UMq8ofCstMQ&list=RDUMq8ofCstMQ&start_radio=1"),
("La noia \nMaa: Italy\nVuosi: 2024 \nSija: Top10, 7", Pohja + Top10, "https://www.youtube.com/watch?v=zp1FXHjkjpQ&list=RDzp1FXHjkjpQ&start_radio=1"),
("Jako \nMaa: Armenia\nVuosi: 2024 \nSija: Top10, 8", Pohja + Top10, "https://www.youtube.com/watch?v=hAYXDoZzAyE&list=RDhAYXDoZzAyE&start_radio=1"),
("Unforgettable \nMaa: Sweden\nVuosi: 2024 \nSija: Top10, 9", Pohja + Top10, "https://www.youtube.com/watch?v=DcZpzObYzxs&list=RDDcZpzObYzxs&start_radio=1"),
("Grito \nMaa: Portugal\nVuosi: 2024 \nSija: Top10, 10", Pohja + Top10, "https://www.youtube.com/watch?v=OZn4-H6JvKU&list=RDOZn4-H6JvKU&start_radio=1"),
("Due vite \nMaa: Italy\nVuosi: 2023 \nSija: Top10, 4", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=d6IiOSut_4M&list=RDd6IiOSut_4M&start_radio=1"),
("Queen of Kings \nMaa: Norway\nVuosi: 2023 \nSija: Top10, 5", Pohja + Top10, "https://www.youtube.com/watch?v=PUHSM_vTqTI&list=RDPUHSM_vTqTI&start_radio=1"),
("Heart of Steel \nMaa: Ukraine\nVuosi: 2023 \nSija: Top10, 6", Pohja + Top10, "https://www.youtube.com/watch?v=I2oqDpefJ1s&list=RDI2oqDpefJ1s&start_radio=1"),
("Because of You \nMaa: Belgium\nVuosi: 2023 \nSija: Top10, 7", Pohja + Top10, "https://www.youtube.com/watch?v=U1xD14IMKtg&list=RDU1xD14IMKtg&start_radio=1"),
("Bridges \nMaa: Estonia\nVuosi: 2023 \nSija: Top10, 8", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=HsbC-OYMA3s&list=RDHsbC-OYMA3s&start_radio=1"),
("Promise \nMaa: Australia\nVuosi: 2023 \nSija: Top10, 9", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=GSoy_mJMlMY&list=RDGSoy_mJMlMY&start_radio=1"),
("My Sister's Crown \nMaa: Czechia\nVuosi: 2023 \nSija: Top10, 10", Pohja + Top10, "https://www.youtube.com/watch?v=ag8qxpvTTy0&list=RDag8qxpvTTy0&start_radio=1"),
("Hold Me Closer \nMaa: Sweden\nVuosi: 2022 \nSija: Top10, 4", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=i777psA2gP4&list=RDi777psA2gP4&start_radio=1"),
("In corpore sano \nMaa: Serbia\nVuosi: 2022 \nSija: Top10, 5", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=nBtQj1MfNYA&list=RDnBtQj1MfNYA&start_radio=1"),
("Brividi \nMaa: Italy\nVuosi: 2022 \nSija: Top10, 6", Pohja + Top10, "https://www.youtube.com/watch?v=blEy4xHuMbY&list=RDblEy4xHuMbY&start_radio=1"),
("Trenulețul \nMaa: Moldova\nVuosi: 2022 \nSija: Top10, 7", Pohja + Top10, "https://www.youtube.com/watch?v=DUqf_zO2QaI&list=RDDUqf_zO2QaI&start_radio=1"),
("Die Together \nMaa: Greece\nVuosi: 2022 \nSija: Top10, 8", Pohja + Top10, "https://www.youtube.com/watch?v=BWeT0nJpB3Y&list=RDBWeT0nJpB3Y&start_radio=1"),
("Saudade saudade \nMaa: Portugal\nVuosi: 2022 \nSija: Top10, 9", Pohja + Top10, "https://www.youtube.com/watch?v=mZtbD47u6yI&list=RDmZtbD47u6yI&start_radio=1"),
("Give That Wolf a Banana \nMaa: Norway\nVuosi: 2022 \nSija: Top10, 10", Pohja + Top10, "https://www.youtube.com/watch?v=adCU2rQyDeY&list=RDadCU2rQyDeY&start_radio=1"),
("10 Years \nMaa: Iceland\nVuosi: 2021 \nSija: Top10, 4", Pohja + Top10, "https://www.youtube.com/watch?v=YSMhu-PrLME&list=RDYSMhu-PrLME&start_radio=1"),
("Shum \nMaa: Ukraine\nVuosi: 2021 \nSija: Top10, 5", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=lqvzDkgok_g&list=RDlqvzDkgok_g&start_radio=1"),
("Dark Side \nMaa: Finland\nVuosi: 2021 \nSija: Top10, 6", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=fOPGxQ4fgVw&list=RDfOPGxQ4fgVw&start_radio=1"),
("Je me casse \nMaa: Malta\nVuosi: 2021 \nSija: Top10, 7", Pohja + Top10, "https://www.youtube.com/watch?v=jbbc2yKnv0M&list=RDjbbc2yKnv0M&start_radio=1"),
("Discoteque \nMaa: Lithuania\nVuosi: 2021 \nSija: Top10, 8", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=JNweec5olYw&list=RDJNweec5olYw&start_radio=1"),
("Russian Woman \nMaa: Russia\nVuosi: 2021 \nSija: Top10, 9", Pohja + Top10, "https://www.youtube.com/watch?v=V-Di9A28e5E&list=RDV-Di9A28e5E&start_radio=1"),
("Last Dance \nMaa: Greece\nVuosi: 2021 \nSija: Top10, 10", Pohja + Top10, "https://www.youtube.com/watch?v=QhZhJFp0vVw&list=RDQhZhJFp0vVw&start_radio=1"),
("She Got Me \nMaa: Switzerland\nVuosi: 2019 \nSija: Top10, 4", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=8aUYzqAIdoM&list=RD8aUYzqAIdoM&start_radio=1"),
("Too Late for Love \nMaa: Sweden\nVuosi: 2019 \nSija: Top10, 5", Pohja + Top10, "https://www.youtube.com/watch?v=oEdWkdVKIqQ&list=RDoEdWkdVKIqQ&start_radio=1"),
("Spirit in the Sky \nMaa: Norway\nVuosi: 2019 \nSija: Top10, 6", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=Ovt7YGHAj8I&list=RDOvt7YGHAj8I&start_radio=1"),
("Proud \nMaa: N.Macedonia\nVuosi: 2019 \nSija: Top10, 7", Pohja + Top10, "https://www.youtube.com/watch?v=0pAURAsum4A&list=RD0pAURAsum4A&start_radio=1"),
("Truth \nMaa: Azerbaijan\nVuosi: 2019 \nSija: Top10, 8", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=D6vvuCiHwSs&list=RDD6vvuCiHwSs&start_radio=1"),
("Zero Gravity \nMaa: Australia\nVuosi: 2019 \nSija: Top10, 9", Pohja + Top10, "https://www.youtube.com/watch?v=Eo5H62mCIsg&list=RDEo5H62mCIsg&start_radio=1"),
("Hatrið mun sigra \nMaa: Iceland\nVuosi: 2019 \nSija: Top10, 10", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=kTb69WkBbvs&list=RDkTb69WkBbvs&start_radio=1"),
("You Let Me Walk Alone \nMaa: Germany\nVuosi: 2018 \nSija: Top10, 4", Pohja + Top10, "https://www.youtube.com/watch?v=N4YwSy4Q9k0&list=RDN4YwSy4Q9k0&start_radio=1"),
("Non mi avete fatto niente \nMaa: Italy\nVuosi: 2018 \nSija: Top10, 5", Pohja + Top10, "https://www.youtube.com/watch?v=81M-mp5t8uM&list=RD81M-mp5t8uM&start_radio=1"),
("Lie to Me \nMaa: Czechia\nVuosi: 2018 \nSija: Top10, 6", Pohja + Top10, "https://www.youtube.com/watch?v=w0ZUuQe0shk&list=RDw0ZUuQe0shk&start_radio=1"),
("Dance You Off \nMaa: Sweden\nVuosi: 2018 \nSija: Top10, 7", Pohja + Top10, "https://www.youtube.com/watch?v=z101xtUBflU&list=RDz101xtUBflU&start_radio=1"),
("La forza \nMaa: Estonia\nVuosi: 2018 \nSija: Top10, 8", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=ImawXdXIGd8&list=RDImawXdXIGd8&start_radio=1"),
("Higher Ground \nMaa: Denmark\nVuosi: 2018 \nSija: Top10, 9", Pohja + Top10, "https://www.youtube.com/watch?v=c0kP074Mw0k&list=RDc0kP074Mw0k&start_radio=1"),
("My Lucky Day \nMaa: Moldova\nVuosi: 2018 \nSija: Top10, 10", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=5evrVL1rJPA&list=RD5evrVL1rJPA&start_radio=1"),
("City Lights \nMaa: Belgium\nVuosi: 2017 \nSija: Top10, 4", Pohja + Top10, "https://www.youtube.com/watch?v=oxsCmChDYwA&list=RDoxsCmChDYwA&start_radio=1"),
("I Can't Go On \nMaa: Sweden\nVuosi: 2017 \nSija: Top10, 5", Pohja + Top10, "https://www.youtube.com/watch?v=yqSV81kmsbQ&list=RDyqSV81kmsbQ&start_radio=1"),
("Occidentali's Karma \nMaa: Italy\nVuosi: 2017 \nSija: Top10, 6", Pohja + Top10, "https://www.youtube.com/watch?v=KieE_MLv-ZY&list=RDKieE_MLv-ZY&start_radio=1"),
("Yodel It! \nMaa: Romania\nVuosi: 2017 \nSija: Top10, 7", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=ZSHc7iDuBCQ&list=RDZSHc7iDuBCQ&start_radio=1"),
("Origo \nMaa: Hungary\nVuosi: 2017 \nSija: Top10, 8", Pohja + Top10, "https://www.youtube.com/watch?v=hqM0AkP7zcI&list=RDhqM0AkP7zcI&start_radio=1"),
("Don't Come Easy \nMaa: Australia\nVuosi: 2017 \nSija: Top10, 9", Pohja + Top10, "https://www.youtube.com/watch?v=YTCP4S1dqwA&list=RDYTCP4S1dqwA&start_radio=1"),
("Grab the Moment \nMaa: Norway\nVuosi: 2017 \nSija: Top10, 10", Pohja + Top10, "https://www.youtube.com/watch?v=U-Bk0PCotY0&list=RDU-Bk0PCotY0&start_radio=1"),
("If Love Was a Crime \nMaa: Bulgaria\nVuosi: 2016 \nSija: Top10, 4", Pohja + Top10, "https://www.youtube.com/watch?v=PQqUTigWKHY&list=RDPQqUTigWKHY&start_radio=1"),
("If I Were Sorry \nMaa: Sweden\nVuosi: 2016 \nSija: Top10, 5", Pohja + Top10, "https://www.youtube.com/watch?v=2AIPrVchJN8&list=RD2AIPrVchJN8&start_radio=1"),
("J'ai cherché \nMaa: France\nVuosi: 2016 \nSija: Top10, 6", Pohja + Top10, "https://www.youtube.com/watch?v=-aLPsiyavcU&list=RD-aLPsiyavcU&start_radio=1"),
("LoveWave \nMaa: Armenia\nVuosi: 2016 \nSija: Top10, 7", Pohja + Top10, "https://www.youtube.com/watch?v=nL066Rp7J7k&list=RDnL066Rp7J7k&start_radio=1"),
("Color of Your Life \nMaa: Poland\nVuosi: 2016 \nSija: Top10, 8", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=87BBmxm7IJU&list=RD87BBmxm7IJU&start_radio=1"),
("I've Been Waiting for This Night \nMaa: Lithuania\nVuosi: 2016 \nSija: Top10, 9", Pohja + Top10, "https://www.youtube.com/watch?v=O1wS7NNCo38&list=RDO1wS7NNCo38&start_radio=1"),
("What's the Pressure \nMaa: Belgium\nVuosi: 2016 \nSija: Top10, 10", Pohja + Top10, "https://www.youtube.com/watch?v=xDBjhAGaeWg&list=RDxDBjhAGaeWg&start_radio=1"),
("Rhythm Inside \nMaa: Belgium\nVuosi: 2015 \nSija: Top10, 4", Pohja + Top10, "https://www.youtube.com/watch?v=G48p8eNhnd8&list=RDG48p8eNhnd8&start_radio=1"),
("Tonight Again \nMaa: Australia\nVuosi: 2015 \nSija: Top10, 5", Pohja + Top10, "https://www.youtube.com/watch?v=H0EhhZWXTng&list=RDH0EhhZWXTng&start_radio=1"),
("Love Injected \nMaa: Latvia\nVuosi: 2015 \nSija: Top10, 6", Pohja + Top10, "https://www.youtube.com/watch?v=-usdXbeGHi8&list=RD-usdXbeGHi8&start_radio=1"),
("Goodbye to Yesterday \nMaa: Estonia\nVuosi: 2015 \nSija: Top10, 7", Pohja + Top10, "https://www.youtube.com/watch?v=Xsx_dIJOtgI&list=RDXsx_dIJOtgI&start_radio=1"),
("A Monster Like Me \nMaa: Norway\nVuosi: 2015 \nSija: Top10, 8", Pohja + Top10, "https://www.youtube.com/watch?v=vY1FCXDojMU&list=RDvY1FCXDojMU&start_radio=1"),
("Golden Boy \nMaa: Israel\nVuosi: 2015 \nSija: Top10, 9", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=-w-2K9U8UIs&list=RD-w-2K9U8UIs&start_radio=1"),
("Beauty Never Lies \nMaa: Serbia\nVuosi: 2015 \nSija: Top10, 10", Pohja + Top10, "https://www.youtube.com/watch?v=c40kVKIoPvE&list=RDc40kVKIoPvE&start_radio=1"),
("Not Alone \nMaa: Armenia\nVuosi: 2014 \nSija: Top10, 4", Pohja + Top10, "https://www.youtube.com/watch?v=oj0oOV-2fRQ&list=RDoj0oOV-2fRQ&start_radio=1"),
("Running \nMaa: Hungary\nVuosi: 2014 \nSija: Top10, 5", Pohja + Top10, "https://www.youtube.com/watch?v=T_RxJZ3N9kE&list=RDT_RxJZ3N9kE&start_radio=1"),
("Tick-Tock \nMaa: Ukraine\nVuosi: 2014 \nSija: Top10, 6", Pohja + Top10, "https://www.youtube.com/watch?v=slHboKF9PIQ&list=RDslHboKF9PIQ&start_radio=1"),
("Shine \nMaa: Russia\nVuosi: 2014 \nSija: Top10, 7", Pohja + Top10, "https://www.youtube.com/watch?v=y5yTMGxFiPw&list=RDy5yTMGxFiPw&start_radio=1"),
("Silent Storm \nMaa: Norway\nVuosi: 2014 \nSija: Top10, 8", Pohja + Top10, "https://www.youtube.com/watch?v=BTMli8U17MM&list=RDBTMli8U17MM&start_radio=1"),
("Cliche Love Song \nMaa: Denmark\nVuosi: 2014 \nSija: Top10, 9", Pohja + Top10, "https://www.youtube.com/watch?v=jnCTsJkieY4&list=RDjnCTsJkieY4&start_radio=1"),
("Dancing in the Rain \nMaa: Spain\nVuosi: 2014 \nSija: Top10, 10", Pohja + Top10, "https://www.youtube.com/watch?v=LY4n5FUlfDQ&list=RDLY4n5FUlfDQ&start_radio=1"),
("I Feed You My Love \nMaa: Norway\nVuosi: 2013 \nSija: Top10, 4", Pohja + Top10, "https://www.youtube.com/watch?v=tc6a4EV63uM&list=RDtc6a4EV63uM&start_radio=1"),
("What If \nMaa: Russia\nVuosi: 2013 \nSija: Top10, 5", Pohja + Top10, "https://www.youtube.com/watch?v=wHNwk3Oez8U&list=RDwHNwk3Oez8U&start_radio=1"),
("Alcohol Is Free \nMaa: Greece\nVuosi: 2013 \nSija: Top10, 6", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=_AfrOZersNk&list=RD_AfrOZersNk&start_radio=1"),
("L'essenziale \nMaa: Italy\nVuosi: 2013 \nSija: Top10, 7", Pohja + Top10, "https://www.youtube.com/watch?v=S8oaxDV1q6o&list=RDS8oaxDV1q6o&start_radio=1"),
("Tomorrow \nMaa: Malta\nVuosi: 2013 \nSija: Top10, 8", Pohja + Top10, "https://www.youtube.com/watch?v=VK4TvZeL6c0&list=RDVK4TvZeL6c0&start_radio=1"),
("Birds \nMaa: Netherlands\nVuosi: 2013 \nSija: Top10, 9", Pohja + Top10, "https://www.youtube.com/watch?v=n5iazXvMw5o&list=RDn5iazXvMw5o&start_radio=1"),
("Kedvesem \nMaa: Hungary\nVuosi: 2013 \nSija: Top10, 10", Pohja + Top10, "https://www.youtube.com/watch?v=rOimfHq76xk&list=RDrOimfHq76xk&start_radio=1"),
("When the Music Dies \nMaa: Azerbaijan\nVuosi: 2012 \nSija: Top10, 4", Pohja + Top10, "https://www.youtube.com/watch?v=yzT7O3Fnwpk&list=RDyzT7O3Fnwpk&start_radio=1"),
("Suus \nMaa: Albania\nVuosi: 2012 \nSija: Top10, 5", Pohja + Top10, "https://www.youtube.com/watch?v=QeBL2UHhyEc&list=RDQeBL2UHhyEc&start_radio=1"),
("Kuula \nMaa: Estonia\nVuosi: 2012 \nSija: Top10, 6", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=T7BaTBe0UD8&list=RDT7BaTBe0UD8&start_radio=1"),
("Love Me Back \nMaa: Turkey\nVuosi: 2012 \nSija: Top10, 7", Pohja + Top10, "https://www.youtube.com/watch?v=3Qa7_y21oOY&list=RD3Qa7_y21oOY&start_radio=1"),
("Standing Still \nMaa: Germany\nVuosi: 2012 \nSija: Top10, 8", Pohja + Top10, "https://www.youtube.com/watch?v=cScJPH20P3A&list=RDcScJPH20P3A&start_radio=1"),
("L'amore è femmina (Out of Love) \nMaa: Italy\nVuosi: 2012 \nSija: Top10, 9", Pohja + Top10, "https://www.youtube.com/watch?v=v0kGpDEvtbQ&list=RDv0kGpDEvtbQ&start_radio=1"),
("Quédate conmigo \nMaa: Spain\nVuosi: 2012 \nSija: Top10, 10", Pohja + Top10, "https://www.youtube.com/watch?v=U8J1b62wOao&list=RDU8J1b62wOao&start_radio=1"),
("Angel \nMaa: Ukraine\nVuosi: 2011 \nSija: Top10, 4", Pohja + Top10, "https://www.youtube.com/watch?v=mx1wAj_oVdE&list=RDmx1wAj_oVdE&start_radio=1"),
("New Tomorrow \nMaa: Denmark\nVuosi: 2011 \nSija: Top10, 5", Pohja + Top10, "https://www.youtube.com/watch?v=YDXeK0r3aKs&list=RDYDXeK0r3aKs&start_radio=1"),
("Love in Rewind \nMaa: Bosnia & Herz.\nVuosi: 2011 \nSija: Top10, 6", Pohja + Top10, "https://www.youtube.com/watch?v=1VCS-qa1RGs&list=RD1VCS-qa1RGs&start_radio=1"),
("Watch My Dance \nMaa: Greece\nVuosi: 2011 \nSija: Top10, 7", Pohja + Top10, "https://www.youtube.com/watch?v=FdZzklXoAOg&list=RDFdZzklXoAOg&start_radio=1"),
("Lipstick \nMaa: Ireland\nVuosi: 2011 \nSija: Top10, 8", Pohja + Top10, "https://www.youtube.com/watch?v=rEyd-DVLq9M&list=RDrEyd-DVLq9M&start_radio=1"),
("One More Day \nMaa: Georgia\nVuosi: 2011 \nSija: Top10, 9", Pohja + Top10 + Suosikki, "https://www.youtube.com/watch?v=s2EwiTBiEDU&list=RDs2EwiTBiEDU&start_radio=1"),
("Taken by a Stranger \nMaa: Germany\nVuosi: 2011 \nSija: Top10, 10", Pohja + Top10, "https://www.youtube.com/watch?v=KqZprvpWlcE&list=RDKqZprvpWlcE&start_radio=1"),
("In a Moment like This \nMaa: Denmark\nVuosi: 2010 \nSija: Top10, 4", Pohja + Top10, "https://www.youtube.com/watch?v=Px2UsvO1lCg&list=RDPx2UsvO1lCg&start_radio=1"),
("Drip Drop \nMaa: Azerbaijan\nVuosi: 2010 \nSija: Top10, 5", Pohja + Top10, "https://www.youtube.com/watch?v=SOKGZb38e5c&list=RDSOKGZb38e5c&start_radio=1"),
("Me and My Guitar \nMaa: Belgium\nVuosi: 2010 \nSija: Top10, 6", Pohja + Top10, "https://www.youtube.com/watch?v=lTsnwGrPKEI&list=RDlTsnwGrPKEI&start_radio=1"),
("Apricot Stone \nMaa: Armenia\nVuosi: 2010 \nSija: Top10, 7", Pohja + Top10, "https://www.youtube.com/watch?v=A60atIirQAw&list=RDA60atIirQAw&start_radio=1"),
("Opa \nMaa: Greece\nVuosi: 2010 \nSija: Top10, 8", Pohja + Top10, "https://www.youtube.com/watch?v=wfqOrMlwOjs&list=RDwfqOrMlwOjs&start_radio=1"),
("Shine \nMaa: Georgia\nVuosi: 2010 \nSija: Top10, 9", Pohja + Top10, "https://www.youtube.com/watch?v=y5yTMGxFiPw&list=RDy5yTMGxFiPw&start_radio=1"),
("Sweet People \nMaa: Ukraine\nVuosi: 2010 \nSija: Top10, 10", Pohja + Top10, "https://www.youtube.com/watch?v=20CPPV_uwmE&list=RD20CPPV_uwmE&start_radio=1"),

("Ich Komme \nMaa: Finland\nVuosi: 2025 \nSija: Finaali, 11", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=V3vbVd1ynnk&list=RDV3vbVd1ynnk&start_radio=1"),
("C'est La Vie \nMaa: Netherlands\nVuosi: 2025 \nSija: Finaali, 12", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=LiTQVJwxvfE&list=RDLiTQVJwxvfE&start_radio=1"),
("Bur Man Laimi \nMaa: Latvia\nVuosi: 2025 \nSija: Finaali, 13", Pohja + Finaali, "https://www.youtube.com/watch?v=nkvcMe3NiQ0&list=RDnkvcMe3NiQ0&start_radio=1"),
("Gaja \nMaa: Poland\nVuosi: 2025 \nSija: Finaali, 14", Pohja + Finaali, "https://www.youtube.com/watch?v=NQXhvclWuPE&list=RDNQXhvclWuPE&start_radio=1"),
("Baller \nMaa: Germany\nVuosi: 2025 \nSija: Finaali, 15", Pohja + Finaali, "https://www.youtube.com/watch?v=3rrWZ6cldsA&list=RD3rrWZ6cldsA&start_radio=1"),
("Tavo Akys \nMaa: Lithuania\nVuosi: 2025 \nSija: Finaali, 16", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=3F6bwWGhm_s&list=RD3F6bwWGhm_s&start_radio=1"),
("Serving \nMaa: Malta\nVuosi: 2025 \nSija: Finaali, 17", Pohja + Finaali, "https://www.youtube.com/watch?v=povnGP6k0sI&list=RDpovnGP6k0sI&start_radio=1"),
("Lighter \nMaa: Norway\nVuosi: 2025 \nSija: Finaali, 18", Pohja + Finaali, "https://www.youtube.com/watch?v=gQOGxx6Fk9k&list=RDgQOGxx6Fk9k&start_radio=1"),
("What The Hell Just Happened? \nMaa: United Kingdom\nVuosi: 2025 \nSija: Finaali, 19", Pohja + Finaali, "https://www.youtube.com/watch?v=Ur5qRh0BaHk&list=RDUr5qRh0BaHk&start_radio=1"),
("Survivor \nMaa: Armenia\nVuosi: 2025 \nSija: Finaali, 20", Pohja + Finaali, "https://www.youtube.com/watch?v=qHkZWLld-pw&list=RDqHkZWLld-pw&start_radio=1"),
("Deslocado \nMaa: Portugal\nVuosi: 2025 \nSija: Finaali, 21", Pohja + Finaali, "https://www.youtube.com/watch?v=waInyqBwSo0&list=RDwaInyqBwSo0&start_radio=1"),
("La Poupee Monte Le Son \nMaa: Luxembourg\nVuosi: 2025 \nSija: Finaali, 22", Pohja + Finaali, "https://www.youtube.com/watch?v=GT7ZZBCscUg&list=RDGT7ZZBCscUg&start_radio=1"),
("Hallucination \nMaa: Denmark\nVuosi: 2025 \nSija: Finaali, 23", Pohja + Finaali, "https://www.youtube.com/watch?v=B3BdsYDnS8M&list=RDB3BdsYDnS8M&start_radio=1"),
("Esa Diva \nMaa: Spain\nVuosi: 2025 \nSija: Finaali, 24", Pohja + Finaali, "https://www.youtube.com/watch?v=IEKSa9FVLqA&list=RDIEKSa9FVLqA&start_radio=1"),
("Roa \nMaa: Iceland\nVuosi: 2025 \nSija: Finaali, 25", Pohja + Finaali, "https://www.youtube.com/watch?v=c73Lx1QUZZA&list=RDc73Lx1QUZZA&start_radio=1"),
("Tutta l'Italia \nMaa: San Marino\nVuosi: 2025 \nSija: Finaali, 26", Pohja + Finaali, "https://www.youtube.com/watch?v=hq6XIRKmA2A&list=RDhq6XIRKmA2A&start_radio=1"),
("Zari \nMaa: Greece\nVuosi: 2024 \nSija: Finaali, 11", Pohja + Finaali, "https://www.youtube.com/watch?v=ENb4LCeq9Lc&list=RDENb4LCeq9Lc&start_radio=1"),
("Always on the Run \nMaa: Germany\nVuosi: 2024 \nSija: Finaali, 12", Pohja + Finaali, "https://www.youtube.com/watch?v=kVOHTxFOhak&list=RDkVOHTxFOhak&start_radio=1"),
("Fighter \nMaa: Luxembourg\nVuosi: 2024 \nSija: Finaali, 13", Pohja + Finaali, "https://www.youtube.com/watch?v=TCWH3Nq5y9A&list=RDTCWH3Nq5y9A&start_radio=1"),
("Luktelk \nMaa: Lithuania\nVuosi: 2024 \nSija: Finaali, 14", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=N8YuQzJLR_k&list=RDN8YuQzJLR_k&start_radio=1"),
("Liar \nMaa: Cyprus\nVuosi: 2024 \nSija: Finaali, 15", Pohja + Finaali, "https://www.youtube.com/watch?v=c4wMioZXbMk&list=RDc4wMioZXbMk&start_radio=1"),
("Hollow \nMaa: Latvia\nVuosi: 2024 \nSija: Finaali, 16", Pohja + Finaali, "https://www.youtube.com/watch?v=kgIwQkMwURY&list=RDkgIwQkMwURY&start_radio=1"),
("Ramonda \nMaa: Serbia\nVuosi: 2024 \nSija: Finaali, 17", Pohja + Finaali, "https://www.youtube.com/watch?v=4hUg64uIY_4&list=RD4hUg64uIY_4&start_radio=1"),
("Dizzy \nMaa: United Kingdom\nVuosi: 2024 \nSija: Finaali, 18", Pohja + Finaali, "https://www.youtube.com/watch?v=q0_FdJqyQW0&list=RDq0_FdJqyQW0&start_radio=1"),
("No Rules! \nMaa: Finland\nVuosi: 2024 \nSija: Finaali, 19", Pohja + Finaali, "https://www.youtube.com/watch?v=7nidDtyS0Wo&list=RD7nidDtyS0Wo&start_radio=1"),
("(Nendest) narkootikumidest ei tea me (küll) midagi \nMaa: Estonia\nVuosi: 2024 \nSija: Finaali, 20", Pohja + Finaali, "https://www.youtube.com/watch?v=RSMMU2wX0Bk&list=RDRSMMU2wX0Bk&start_radio=1"),
("Firefighter \nMaa: Georgia\nVuosi: 2024 \nSija: Finaali, 21", Pohja + Finaali, "https://www.youtube.com/watch?v=He4PGhm7jOw&list=RDHe4PGhm7jOw&start_radio=1"),
("Zorra \nMaa: Spain\nVuosi: 2024 \nSija: Finaali, 22", Pohja + Finaali, "https://www.youtube.com/watch?v=FOMoQoHG5aU&list=RDFOMoQoHG5aU&start_radio=1"),
("Veronika \nMaa: Slovenia\nVuosi: 2024 \nSija: Finaali, 23", Pohja + Finaali, "https://www.youtube.com/watch?v=l86DxpRnz5M&list=RDl86DxpRnz5M&start_radio=1"),
("We Will Rave \nMaa: Austria\nVuosi: 2024 \nSija: Finaali, 24", Pohja + Finaali, "https://www.youtube.com/watch?v=VZ6SlZnk_EI&list=RDVZ6SlZnk_EI&start_radio=1"),
("Ulveham \nMaa: Norway\nVuosi: 2024 \nSija: Finaali, 25", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=YBbL8ORqNVU&list=RDYBbL8ORqNVU&start_radio=1"),
("Europapa \nMaa: Belgium\nVuosi: 2024 \nSija: Finaali, ?", Pohja + Finaali, "https://www.youtube.com/watch?v=IiHFnmI8pxg&list=RDIiHFnmI8pxg&start_radio=1"),
("Stay \nMaa: Lithuania\nVuosi: 2023 \nSija: Finaali, 11", Pohja + Finaali, "https://www.youtube.com/watch?v=QsgouAEd34U&list=RDQsgouAEd34U&start_radio=1"),
("Break a Broken Heart \nMaa: Cyprus\nVuosi: 2023 \nSija: Finaali, 12", Pohja + Finaali, "https://www.youtube.com/watch?v=49YiimKeyDI&list=RD49YiimKeyDI&start_radio=1"),
("Mama ŠČ! \nMaa: Croatia\nVuosi: 2023 \nSija: Finaali, 13", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=hGuGfdEJ5Pw&list=RDhGuGfdEJ5Pw&start_radio=1"),
("Future Lover \nMaa: Armenia\nVuosi: 2023 \nSija: Finaali, 14", Pohja + Finaali, "https://www.youtube.com/watch?v=h0q7AkYk2hY&list=RDh0q7AkYk2hY&start_radio=1"),
("Who the Hell Is Edgar? \nMaa: Austria\nVuosi: 2023 \nSija: Finaali, 15", Pohja + Finaali, "https://www.youtube.com/watch?v=8uk64V9h0Ko&list=RD8uk64V9h0Ko&start_radio=1"),
("Évidemment \nMaa: France\nVuosi: 2023 \nSija: Finaali, 16", Pohja + Finaali, "https://www.youtube.com/watch?v=fOtQJ4o-HoA&list=RDfOtQJ4o-HoA&start_radio=1"),
("Eaea \nMaa: Spain\nVuosi: 2023 \nSija: Finaali, 17", Pohja + Finaali, "https://www.youtube.com/watch?v=Vw6qPWhjevk&list=RDVw6qPWhjevk&start_radio=1"),
("Soarele și luna \nMaa: Moldova\nVuosi: 2023 \nSija: Finaali, 18", Pohja + Finaali, "https://www.youtube.com/watch?v=SABOfYgGk8M&list=RDSABOfYgGk8M&start_radio=1"),
("Solo \nMaa: Poland\nVuosi: 2023 \nSija: Finaali, 19", Pohja + Finaali, "https://www.youtube.com/watch?v=SEgF1aP-U1o&list=RDSEgF1aP-U1o&start_radio=1"),
("Watergun \nMaa: Switzerland\nVuosi: 2023 \nSija: Finaali, 20", Pohja + Finaali, "https://www.youtube.com/watch?v=l4NDErv49mk&list=RDl4NDErv49mk&start_radio=1"),
("Carpe Diem \nMaa: Slovenia\nVuosi: 2023 \nSija: Finaali, 21", Pohja + Finaali, "https://www.youtube.com/watch?v=3LXlPviGiWc&list=RD3LXlPviGiWc&start_radio=1"),
("Duje \nMaa: Albania\nVuosi: 2023 \nSija: Finaali, 22", Pohja + Finaali, "https://www.youtube.com/watch?v=TI9rSDhXwyc&list=RDTI9rSDhXwyc&start_radio=1"),
("Ai coração \nMaa: Portugal\nVuosi: 2023 \nSija: Finaali, 23", Pohja + Finaali, "https://www.youtube.com/watch?v=HYfkxX4PFyw&list=RDHYfkxX4PFyw&start_radio=1"),
("Samo mi se spava \nMaa: Serbia\nVuosi: 2023 \nSija: Finaali, 24", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=E89gtz9rdBM&list=RDE89gtz9rdBM&start_radio=1"),
("I Wrote a Song \nMaa: United Kingdom\nVuosi: 2023 \nSija: Finaali, 25", Pohja + Finaali, "https://www.youtube.com/watch?v=tvJEE2ryCRQ&list=RDtvJEE2ryCRQ&start_radio=1"),
("Blood & Glitter \nMaa: Germany\nVuosi: 2023 \nSija: Finaali, 26", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=dyGR4YWlPEs&list=RDdyGR4YWlPEs&start_radio=1"),
("De diepte \nMaa: Netherland\nVuosi: 2022 \nSija: Finaali, 11", Pohja + Finaali, "https://www.youtube.com/watch?v=sgOnu7ux2-k&list=RDsgOnu7ux2-k&start_radio=1"),
("River \nMaa: Poland\nVuosi: 2022 \nSija: Finaali, 12", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=jRVDZ6446eM&list=RDjRVDZ6446eM&start_radio=1"),
("Hope \nMaa: Estonia\nVuosi: 2022 \nSija: Finaali, 13", Pohja + Finaali, "https://www.youtube.com/watch?v=GdTpQmMem8U&list=RDGdTpQmMem8U&start_radio=1"),
("Sentimentai \nMaa: Lithuania\nVuosi: 2022 \nSija: Finaali, 14", Pohja + Finaali, "https://www.youtube.com/watch?v=BVqSTVJhD44&list=RDBVqSTVJhD44&start_radio=1"),
("Not the Same \nMaa: Australia\nVuosi: 2022 \nSija: Finaali, 15", Pohja + Finaali, "https://www.youtube.com/watch?v=wosfFz2FJPU&list=RDwosfFz2FJPU&start_radio=1"),
("Fade to Black \nMaa: Azerbaijan\nVuosi: 2022 \nSija: Finaali, 16", Pohja + Finaali, "https://www.youtube.com/watch?v=tegPzHEL4ms&list=RDtegPzHEL4ms&start_radio=1"),
("Boys Do Cry \nMaa: Switzerland\nVuosi: 2022 \nSija: Finaali, 17", Pohja + Finaali, "https://www.youtube.com/watch?v=hq2HCmHv5p4&list=RDhq2HCmHv5p4&start_radio=1"),
("Llámame \nMaa: Romania\nVuosi: 2022 \nSija: Finaali, 18", Pohja + Finaali, "https://www.youtube.com/watch?v=nPpuwy79sHs&list=RDnPpuwy79sHs&start_radio=1"),
("Miss You \nMaa: Belgium\nVuosi: 2022 \nSija: Finaali, 19", Pohja + Finaali, "https://www.youtube.com/watch?v=sB09advfF6E&list=RDsB09advfF6E&start_radio=1"),
("Snap \nMaa: Armenia\nVuosi: 2022 \nSija: Finaali, 20", Pohja + Finaali, "https://www.youtube.com/watch?v=DAJ6vfmD_ic&list=RDDAJ6vfmD_ic&start_radio=1"),
("Jezebel \nMaa: Finland\nVuosi: 2022 \nSija: Finaali, 21", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=LSi9nfr65FE&list=RDLSi9nfr65FE&start_radio=1"),
("Lights Off \nMaa: Czechia\nVuosi: 2022 \nSija: Finaali, 22", Pohja + Finaali, "https://www.youtube.com/watch?v=EGRzSefqOm0&list=RDEGRzSefqOm0&start_radio=1"),
("Með hækkandi sól \nMaa: Iceland\nVuosi: 2022 \nSija: Finaali, 23", Pohja + Finaali, "https://www.youtube.com/watch?v=G71c48O3j-s&list=RDG71c48O3j-s&start_radio=1"),
("Fulenn \nMaa: France\nVuosi: 2022 \nSija: Finaali, 24", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=H1lcGXwOqJI&list=RDH1lcGXwOqJI&start_radio=1"),
("Rockstars \nMaa: Germany\nVuosi: 2022 \nSija: Finaali, 25", Pohja + Finaali, "https://www.youtube.com/watch?v=2BYIou-oWXA&list=RD2BYIou-oWXA&start_radio=1"),
("Growing Up Is Getting Old \nMaa: Bulgaria\nVuosi: 2021 \nSija: Finaali, 11", Pohja + Finaali, "https://www.youtube.com/watch?v=B1ZiPrMwMYA&list=RDB1ZiPrMwMYA&start_radio=1"),
("Love Is on My Side \nMaa: Portugal\nVuosi: 2021 \nSija: Finaali, 12", Pohja + Finaali, "https://www.youtube.com/watch?v=qq9SceXaukA&list=RDqq9SceXaukA&start_radio=1"),
("Sugar \nMaa: Moldova\nVuosi: 2021 \nSija: Finaali, 13", Pohja + Finaali, "https://www.youtube.com/watch?v=5I_1GTehgkI&list=RD5I_1GTehgkI&start_radio=1"),
("Voices \nMaa: Sweden\nVuosi: 2021 \nSija: Finaali, 14", Pohja + Finaali, "https://www.youtube.com/watch?v=NyJRyif6_kk&list=RDNyJRyif6_kk&start_radio=1"),
("Loco loco \nMaa: Serbia\nVuosi: 2021 \nSija: Finaali, 15", Pohja + Finaali, "https://www.youtube.com/watch?v=Q1lkpIqf7a4&list=RDQ1lkpIqf7a4&start_radio=1"),
("El Diablo \nMaa: Cyprus\nVuosi: 2021 \nSija: Finaali, 16", Pohja + Finaali, "https://www.youtube.com/watch?v=MgGc1F_cOE8&list=RDMgGc1F_cOE8&start_radio=1"),
("Set Me Free \nMaa: Israel\nVuosi: 2021 \nSija: Finaali, 17", Pohja + Finaali, "https://www.youtube.com/watch?v=5Y-blG5ptwo&list=RD5Y-blG5ptwo&start_radio=1"),
("Fallen Angel \nMaa: Norway\nVuosi: 2021 \nSija: Finaali, 18", Pohja + Finaali, "https://www.youtube.com/watch?v=F0r3vmGLzZU&list=RDF0r3vmGLzZU&start_radio=1"),
("The Wrong Place \nMaa: Belgium\nVuosi: 2021 \nSija: Finaali, 19", Pohja + Finaali, "https://www.youtube.com/watch?v=HbpxcUMtjwY&list=RDHbpxcUMtjwY&start_radio=1"),
("Mata Hari \nMaa: Azerbaijan\nVuosi: 2021 \nSija: Finaali, 20", Pohja + Finaali, "https://www.youtube.com/watch?v=FTQ22S5YC7Q&list=RDFTQ22S5YC7Q&start_radio=1"),
("Karma \nMaa: Albania\nVuosi: 2021 \nSija: Finaali, 21", Pohja + Finaali, "https://www.youtube.com/watch?v=OxniMKVXjqM&list=RDOxniMKVXjqM&start_radio=1"),
("Adrenalina \nMaa: San Marino\nVuosi: 2021 \nSija: Finaali, 22", Pohja + Finaali, "https://www.youtube.com/watch?v=TkhiH-JXFPs&list=RDTkhiH-JXFPs&start_radio=1"),
("Birth of a New Age \nMaa: Netherlands\nVuosi: 2021 \nSija: Finaali, 23", Pohja + Finaali, "https://www.youtube.com/watch?v=o3Da5cr2fTs&list=RDo3Da5cr2fTs&start_radio=1"),
("Voy a quedarme \nMaa: Spain\nVuosi: 2021 \nSija: Finaali, 24", Pohja + Finaali, "https://www.youtube.com/watch?v=thV-vhOQHvQ&list=RDthV-vhOQHvQ&start_radio=1"),
("I Don't Feel Hate \nMaa: Germany\nVuosi: 2021 \nSija: Finaali, 25", Pohja + Finaali, "https://www.youtube.com/watch?v=1m0VEAfLV4E&list=RD1m0VEAfLV4E&start_radio=1"),
("Embers \nMaa: United Kingdom\nVuosi: 2021 \nSija: Finaali, 26", Pohja + Finaali, "https://www.youtube.com/watch?v=VxNOynEJ6wc&list=RDVxNOynEJ6wc&start_radio=1"),
("Friend of a Friend \nMaa: Czechia\nVuosi: 2019 \nSija: Finaali, 11", Pohja + Finaali, "https://www.youtube.com/watch?v=NJxLKFZKhNs&list=RDNJxLKFZKhNs&start_radio=1"),
("Love Is Forever \nMaa: Denmark\nVuosi: 2019 \nSija: Finaali, 12", Pohja + Finaali, "https://www.youtube.com/watch?v=mucmvTLHJQM&list=RDmucmvTLHJQM&start_radio=1"),
("Replay \nMaa: Cyprus\nVuosi: 2019 \nSija: Finaali, 13", Pohja + Finaali, "https://www.youtube.com/watch?v=wIpEI-NhRxg&list=RDwIpEI-NhRxg&start_radio=1"),
("Chameleon \nMaa: Malta\nVuosi: 2019 \nSija: Finaali, 14", Pohja + Finaali, "https://www.youtube.com/watch?v=H-byNyainRA&list=RDH-byNyainRA&start_radio=1"),
("Sebi \nMaa: Slovenia\nVuosi: 2019 \nSija: Finaali, 15", Pohja + Finaali, "https://www.youtube.com/watch?v=vGtPNQ6g6Ng&list=RDvGtPNQ6g6Ng&start_radio=1"),
("Roi \nMaa: France\nVuosi: 2019 \nSija: Finaali, 16", Pohja + Finaali, "https://www.youtube.com/watch?v=AjZNbIQtWvw&list=RDAjZNbIQtWvw&start_radio=1"),
("Ktheju tokës \nMaa: Albania\nVuosi: 2019 \nSija: Finaali, 17", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=-NAbYUoxIfg&list=RD-NAbYUoxIfg&start_radio=1"),
("Kruna \nMaa: Serbia\nVuosi: 2019 \nSija: Finaali, 18", Pohja + Finaali, "https://www.youtube.com/watch?v=X0mdaeAyPvA&list=RDX0mdaeAyPvA&start_radio=1"),
("Say Na Na Na \nMaa: San Marino\nVuosi: 2019 \nSija: Finaali, 19", Pohja + Finaali, "https://www.youtube.com/watch?v=d_iEis_ZRoQ&list=RDd_iEis_ZRoQ&start_radio=1"),
("Storm \nMaa: Estonia\nVuosi: 2019 \nSija: Finaali, 20", Pohja + Finaali, "https://www.youtube.com/watch?v=PppvSl3_W4E&list=RDPppvSl3_W4E&start_radio=1"),
("Better Love \nMaa: Greece\nVuosi: 2019 \nSija: Finaali, 21", Pohja + Finaali, "https://www.youtube.com/watch?v=5pQV_-40m_U&list=RD5pQV_-40m_U&start_radio=1"),
("La venda \nMaa: Spain\nVuosi: 2019 \nSija: Finaali, 22", Pohja + Finaali, "https://www.youtube.com/watch?v=lWXuohnM14U&list=RDlWXuohnM14U&start_radio=1"),
("Home \nMaa: Israel\nVuosi: 2019 \nSija: Finaali, 23", Pohja + Finaali, "https://www.youtube.com/watch?v=uCdS42uCqP0&list=RDuCdS42uCqP0&start_radio=1"),
("Like It \nMaa: Belarus\nVuosi: 2019 \nSija: Finaali, 24", Pohja + Finaali, "https://www.youtube.com/watch?v=C1Y9LBusHzA&list=RDC1Y9LBusHzA&start_radio=1"),
("Sister \nMaa: Germany\nVuosi: 2019 \nSija: Finaali, 25", Pohja + Finaali, "https://www.youtube.com/watch?v=yFbSj_yPCPM&list=RDyFbSj_yPCPM&start_radio=1"),
("Bigger than Us \nMaa: United Kingdom\nVuosi: 2019 \nSija: Finaali, 26", Pohja + Finaali, "https://www.youtube.com/watch?v=HV-eOhTS8Dw&list=RDHV-eOhTS8Dw&start_radio=1"),
("Mall \nMaa: Albania\nVuosi: 2018 \nSija: Finaali, 11", Pohja + Finaali, "https://www.youtube.com/watch?v=uyl1b1fVmdU&list=RDuyl1b1fVmdU&start_radio=1"),
("When We're Old \nMaa: Lithuania\nVuosi: 2018 \nSija: Finaali, 12", Pohja + Finaali, "https://www.youtube.com/watch?v=pPDFhfU25go&list=RDpPDFhfU25go&start_radio=1"),
("Mercy \nMaa: France\nVuosi: 2018 \nSija: Finaali, 13", Pohja + Finaali, "https://www.youtube.com/watch?v=vjLuTtUv0Ns&list=RDvjLuTtUv0Ns&start_radio=1"),
("Bones \nMaa: Bulgaria\nVuosi: 2018 \nSija: Finaali, 14", Pohja + Finaali, "https://www.youtube.com/watch?v=vC-1tdGDFQc&list=RDvC-1tdGDFQc&start_radio=1"),
("That's How You Write a Song \nMaa: Norway\nVuosi: 2018 \nSija: Finaali, 15", Pohja + Finaali, "https://www.youtube.com/watch?v=N17BdRwOvBA&list=RDN17BdRwOvBA&start_radio=1"),
("Together \nMaa: Ireland\nVuosi: 2018 \nSija: Finaali, 16", Pohja + Finaali, "https://www.youtube.com/watch?v=QD1cQ2wZ1dk&list=RDQD1cQ2wZ1dk&start_radio=1"),
("Under the Ladder \nMaa: Ukraine\nVuosi: 2018 \nSija: Finaali, 17", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=lhOuMYtQ94M"),
("Outlaw in 'Em \nMaa: Netherlands\nVuosi: 2018 \nSija: Finaali, 18", Pohja + Finaali, "https://www.youtube.com/watch?v=p7jHz5asMs8&list=RDp7jHz5asMs8&start_radio=1"),
("Nova deca \nMaa: Serbia\nVuosi: 2018 \nSija: Finaali, 19", Pohja + Finaali, "https://www.youtube.com/watch?v=WRQWQShbPHU&list=RDWRQWQShbPHU&start_radio=1"),
("We Got Love \nMaa: Australia\nVuosi: 2018 \nSija: Finaali, 20", Pohja + Finaali, "https://www.youtube.com/watch?v=2BBLTY6T2Ck&list=RD2BBLTY6T2Ck&start_radio=1"),
("Viszlát nyár \nMaa: Hungary\nVuosi: 2018 \nSija: Finaali, 21", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=p6e1TmYb33w&list=RDp6e1TmYb33w&start_radio=1"),
("Hvala, ne! \nMaa: Slovenia\nVuosi: 2018 \nSija: Finaali, 22", Pohja + Finaali, "https://www.youtube.com/watch?v=fBU0_hfST_o&list=RDfBU0_hfST_o&start_radio=1"),
("Tu canción \nMaa: Spain\nVuosi: 2018 \nSija: Finaali, 23", Pohja + Finaali, "https://www.youtube.com/watch?v=28oMEFgSoyk&list=RD28oMEFgSoyk&start_radio=1"),
("Storm \nMaa: United Kingdom\nVuosi: 2018 \nSija: Finaali, 24", Pohja + Finaali, "https://www.youtube.com/watch?v=n0ydtXG-tqY&list=RDn0ydtXG-tqY&start_radio=1"),
("Monsters \nMaa: Finland\nVuosi: 2018 \nSija: Finaali, 25", Pohja + Finaali, "https://www.youtube.com/watch?v=hdjiuCUUpPc&list=RDhdjiuCUUpPc&start_radio=1"),
("O jardim \nMaa: Portugal\nVuosi: 2018 \nSija: Finaali, 26", Pohja + Finaali, "https://www.youtube.com/watch?v=mHjGbADMcOI&list=RDmHjGbADMcOI&start_radio=1"),
("Lights and Shadows \nMaa: Netherlands\nVuosi: 2017 \nSija: Finaali, 11", Pohja + Finaali, "https://www.youtube.com/watch?v=_9XsCqGg8ls&list=RD_9XsCqGg8ls&start_radio=1"),
("Requiem \nMaa: France\nVuosi: 2017 \nSija: Finaali, 12", Pohja + Finaali, "https://www.youtube.com/watch?v=HjiLKsLQl4I&list=RDHjiLKsLQl4I&start_radio=1"),
("My Friend \nMaa: Croatia\nVuosi: 2017 \nSija: Finaali, 13", Pohja + Finaali, "https://www.youtube.com/watch?v=4Sya_GIxsw0&list=RD4Sya_GIxsw0&start_radio=1"),
("Skeletons \nMaa: Azerbaijan\nVuosi: 2017 \nSija: Finaali, 14", Pohja + Finaali, "https://www.youtube.com/watch?v=g_HSRHqd_7s&list=RDg_HSRHqd_7s&start_radio=1"),
("Never Give Up on You \nMaa: United Kingdom\nVuosi: 2017 \nSija: Finaali, 15", Pohja + Finaali, "https://www.youtube.com/watch?v=Fl1GYTg4GmA&list=RDFl1GYTg4GmA&start_radio=1"),
("Running on Air \nMaa: Austria\nVuosi: 2017 \nSija: Finaali, 16", Pohja + Finaali, "https://www.youtube.com/watch?v=gJIjZF5sgzg&list=RDgJIjZF5sgzg&start_radio=1"),
("Story of My Life \nMaa: Belarus\nVuosi: 2017 \nSija: Finaali, 17", Pohja + Finaali, "https://www.youtube.com/watch?v=coFfFZvPmRY&list=RDcoFfFZvPmRY&start_radio=1"),
("Fly with Me \nMaa: Armenia\nVuosi: 2017 \nSija: Finaali, 18", Pohja + Finaali, "https://www.youtube.com/watch?v=g373Libigw8&list=RDg373Libigw8&start_radio=1"),
("This Is Love \nMaa: Greece\nVuosi: 2017 \nSija: Finaali, 19", Pohja + Finaali, "https://www.youtube.com/watch?v=iO14p2uCzkM&list=RDiO14p2uCzkM&start_radio=1"),
("Where I Am \nMaa: Denmark\nVuosi: 2017 \nSija: Finaali, 20", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=vUbGnq8maS0&list=RDvUbGnq8maS0&start_radio=1"),
("Gravity \nMaa: Cyprus\nVuosi: 2017 \nSija: Finaali, 21", Pohja + Finaali, "https://www.youtube.com/watch?v=ZDe9FCLgE04&list=RDZDe9FCLgE04&start_radio=1"),
("Flashlight \nMaa: Poland\nVuosi: 2017 \nSija: Finaali, 22", Pohja + Finaali, "https://www.youtube.com/watch?v=xVCokUW3BUo&list=RDxVCokUW3BUo&start_radio=1"),
("I Feel Alive \nMaa: Israel\nVuosi: 2017 \nSija: Finaali, 23", Pohja + Finaali, "https://www.youtube.com/watch?v=YapnW_zfWJk&list=RDYapnW_zfWJk&start_radio=1"),
("Time \nMaa: Ukraine\nVuosi: 2017 \nSija: Finaali, 24", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=mogNLkIEI0k&list=RDmogNLkIEI0k&start_radio=1"),
("Perfect Life \nMaa: Germany\nVuosi: 2017 \nSija: Finaali, 25", Pohja + Finaali, "https://www.youtube.com/watch?v=t1KKjykH6fw&list=RDt1KKjykH6fw&start_radio=1"),
("Do It for Your Lover \nMaa: Spain\nVuosi: 2017 \nSija: Finaali, 26", Pohja + Finaali, "https://www.youtube.com/watch?v=qAOXHdLdlqQ&list=RDqAOXHdLdlqQ&start_radio=1"),
("Slow Down \nMaa: Netherlands\nVuosi: 2016 \nSija: Finaali, 11", Pohja + Finaali, "https://www.youtube.com/watch?v=PwF9DI89q1w&list=RDPwF9DI89q1w&start_radio=1"),
("Walk on Water \nMaa: Malta\nVuosi: 2016 \nSija: Finaali, 12", Pohja + Finaali, "https://www.youtube.com/watch?v=58YS5m3EYVY&list=RD58YS5m3EYVY&start_radio=1"),
("Loin d'ici \nMaa: Austria\nVuosi: 2016 \nSija: Finaali, 13", Pohja + Finaali, "https://www.youtube.com/watch?v=3xuPYt5i5cE&list=RD3xuPYt5i5cE&start_radio=1"),
("Made of Stars \nMaa: Israel\nVuosi: 2016 \nSija: Finaali, 14", Pohja + Finaali, "https://www.youtube.com/watch?v=SS5TB2XUdgs&list=RDSS5TB2XUdgs&start_radio=1"),
("Heartbeat \nMaa: Latvia\nVuosi: 2016 \nSija: Finaali, 15", Pohja + Finaali, "https://www.youtube.com/watch?v=o-2Lt7zzlBU&list=RDo-2Lt7zzlBU&start_radio=1"),
("No Degree of Separation \nMaa: Italy\nVuosi: 2016 \nSija: Finaali, 16", Pohja + Finaali, "https://www.youtube.com/watch?v=YfnhDfy8AjU&list=RDYfnhDfy8AjU&start_radio=1"),
("Miracle \nMaa: Azerbaijan\nVuosi: 2016 \nSija: Finaali, 17", Pohja + Finaali, "https://www.youtube.com/watch?v=cB8eSLyffsI&list=RDcB8eSLyffsI&start_radio=1"),
("Goodbye (Shelter) \nMaa: Serbia\nVuosi: 2016 \nSija: Finaali, 18", Pohja + Finaali, "https://www.youtube.com/watch?v=yTlxLiSQWjk&list=RDyTlxLiSQWjk&start_radio=1"),
("Pioneer \nMaa: Hungary\nVuosi: 2016 \nSija: Finaali, 19", Pohja + Finaali, "https://www.youtube.com/watch?v=bT2DcpqvorI&list=RDbT2DcpqvorI&start_radio=1"),
("Midnight Gold \nMaa: Georgia\nVuosi: 2016 \nSija: Finaali, 20", Pohja + Finaali, "https://www.youtube.com/watch?v=rviE2-9eiTI&list=RDrviE2-9eiTI&start_radio=1"),
("Alter Ego \nMaa: Cyprus\nVuosi: 2016 \nSija: Finaali, 21", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=idUxTqmCFR0&list=RDidUxTqmCFR0&start_radio=1"),
("Say Yay! \nMaa: Spain\nVuosi: 2016 \nSija: Finaali, 22", Pohja + Finaali, "https://www.youtube.com/watch?v=EgbjNsxehrY&list=RDEgbjNsxehrY&start_radio=1"),
("Lighthouse \nMaa: Croatia\nVuosi: 2016 \nSija: Finaali, 23", Pohja + Finaali, "https://www.youtube.com/watch?v=8QUM-_EbE2o&list=RD8QUM-_EbE2o&start_radio=1"),
("You're Not Alone \nMaa: United Kingdom\nVuosi: 2016 \nSija: Finaali, 24", Pohja + Finaali, "https://www.youtube.com/watch?v=XgGahKsBtts&list=RDXgGahKsBtts&start_radio=1"),
("I Stand \nMaa: Czechia\nVuosi: 2016 \nSija: Finaali, 25", Pohja + Finaali, "https://www.youtube.com/watch?v=wVy3rTNSN4Y&list=RDwVy3rTNSN4Y&start_radio=1"),
("Ghost \nMaa: Germany\nVuosi: 2016 \nSija: Finaali, 26", Pohja + Finaali, "https://www.youtube.com/watch?v=bHDHi37bboE&list=RDbHDHi37bboE&start_radio=1"),
("Warrior \nMaa: Georgia\nVuosi: 2015 \nSija: Finaali, 11", Pohja + Finaali, "https://www.youtube.com/watch?v=ddC8lviTERI&list=RDddC8lviTERI&start_radio=1"),
("Hour of the Wolf \nMaa: Azerbaijan\nVuosi: 2015 \nSija: Finaali, 12", Pohja + Finaali, "https://www.youtube.com/watch?v=IcVrAFtc5YI&list=RDIcVrAFtc5YI&start_radio=1"),
("Adio \nMaa: Montenegro\nVuosi: 2015 \nSija: Finaali, 13", Pohja + Finaali, "https://www.youtube.com/watch?v=MTyi2XeeoJU&list=RDMTyi2XeeoJU&start_radio=1"),
("Here for You \nMaa: Slovenia\nVuosi: 2015 \nSija: Finaali, 14", Pohja + Finaali, "https://www.youtube.com/watch?v=y1c7gDOaFY0&list=RDy1c7gDOaFY0&start_radio=1"),
("De la capăt \nMaa: Romania\nVuosi: 2015 \nSija: Finaali, 15", Pohja + Finaali, "https://www.youtube.com/watch?v=o7iOFkEymXA&list=RDo7iOFkEymXA&start_radio=1"),
("Face the Shadow \nMaa: Armenia\nVuosi: 2015 \nSija: Finaali, 16", Pohja + Finaali, "https://www.youtube.com/watch?v=Z6O8pr7HH94&list=RDZ6O8pr7HH94&start_radio=1"),
("I'm Alive \nMaa: Albania\nVuosi: 2015 \nSija: Finaali, 17", Pohja + Finaali, "https://www.youtube.com/watch?v=fsH9iVaZSaA&list=RDfsH9iVaZSaA&start_radio=1"),
("This Time \nMaa: Lithuania\nVuosi: 2015 \nSija: Finaali, 18", Pohja + Finaali, "https://www.youtube.com/watch?v=xtB_slM63JA&list=RDxtB_slM63JA&start_radio=1"),
("One Last Breath \nMaa: Greece\nVuosi: 2015 \nSija: Finaali, 19", Pohja + Finaali, "https://www.youtube.com/watch?v=qD6epZ-YWSc&list=RDqD6epZ-YWSc&start_radio=1"),
("Wars for Nothing \nMaa: Hungary\nVuosi: 2015 \nSija: Finaali, 20", Pohja + Finaali, "https://www.youtube.com/watch?v=MdybVsBESQc&list=RDMdybVsBESQc&start_radio=1"),
("Amanecer \nMaa: Spain\nVuosi: 2015 \nSija: Finaali, 21", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=NsMiJJlElAY&list=RDNsMiJJlElAY&start_radio=1"),
("One Thing I Should Have Done \nMaa: Cyprus\nVuosi: 2015 \nSija: Finaali, 22", Pohja + Finaali, "https://www.youtube.com/watch?v=RUNEoMBLGc8&list=RDRUNEoMBLGc8&start_radio=1"),
("In the Name of Love \nMaa: Poland\nVuosi: 2015 \nSija: Finaali, 23", Pohja + Finaali, "https://www.youtube.com/watch?v=TReYIZYloSg&list=RDTReYIZYloSg&start_radio=1"),
("Still in Love with You \nMaa: United Kingdom\nVuosi: 2015 \nSija: Finaali, 24", Pohja + Finaali, "https://www.youtube.com/watch?v=s6r1tUhl1cQ&list=RDs6r1tUhl1cQ&start_radio=1"),
("N'oubliez pas \nMaa: France\nVuosi: 2015 \nSija: Finaali, 25", Pohja + Finaali, "https://www.youtube.com/watch?v=tJful-Jtc9o&list=RDtJful-Jtc9o&start_radio=1"),
("I Am Yours \nMaa: Austria\nVuosi: 2015 \nSija: Finaali, 26", Pohja + Finaali, "https://www.youtube.com/watch?v=-f993p0CAV8&list=RD-f993p0CAV8&start_radio=1"),
("Black Smoke \nMaa: Germany\nVuosi: 2015 \nSija: Finaali, 27", Pohja + Finaali, "https://www.youtube.com/watch?v=DGMJOchTRPc&list=RDDGMJOchTRPc&start_radio=1"),
("Something Better \nMaa: Finland\nVuosi: 2014 \nSija: Finaali, 11", Pohja + Finaali, "https://www.youtube.com/watch?v=3FDWaFfo1CU&list=RD3FDWaFfo1CU&start_radio=1"),
("Miracle \nMaa: Romania\nVuosi: 2014 \nSija: Finaali, 12", Pohja + Finaali, "https://www.youtube.com/watch?v=qN2h6__yJGQ&list=RDqN2h6__yJGQ&start_radio=1"),
("Hunter of Stars \nMaa: Switzerland\nVuosi: 2014 \nSija: Finaali, 13", Pohja + Finaali, "https://www.youtube.com/watch?v=DqjoM8ZlyMc&list=RDDqjoM8ZlyMc&start_radio=1"),
("My Słowianie – We Are Slavic \nMaa: Poland\nVuosi: 2014 \nSija: Finaali, 14", Pohja + Finaali, "https://www.youtube.com/watch?v=VJ920cN2HmA&list=RDVJ920cN2HmA&start_radio=1"),
("No Prejudice \nMaa: Iceland\nVuosi: 2014 \nSija: Finaali, 15", Pohja + Finaali, "https://www.youtube.com/watch?v=V5ZG378DH1c&list=RDV5ZG378DH1c&start_radio=1"),
("Cheesecake \nMaa: Belarus\nVuosi: 2014 \nSija: Finaali, 16", Pohja + Finaali, "https://www.youtube.com/watch?v=tImGMW-4eHY&list=RDtImGMW-4eHY&start_radio=1"),
("Children of the Universe \nMaa: United Kingdom\nVuosi: 2014 \nSija: Finaali, 17", Pohja + Finaali, "https://www.youtube.com/watch?v=C6w7tmWvm6M&list=RDC6w7tmWvm6M&start_radio=1"),
("Is It Right \nMaa: Germany\nVuosi: 2014 \nSija: Finaali, 18", Pohja + Finaali, "https://www.youtube.com/watch?v=BFuGH2Kp9dI&list=RDBFuGH2Kp9dI&start_radio=1"),
("Moj svijet \nMaa: Montenegro\nVuosi: 2014 \nSija: Finaali, 19", Pohja + Finaali, "https://www.youtube.com/watch?v=6FJtzRSKHKg&list=RD6FJtzRSKHKg&start_radio=1"),
("Rise Up \nMaa: Greece\nVuosi: 2014 \nSija: Finaali, 20", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=c9y6A1uXLn8&list=RDc9y6A1uXLn8&start_radio=1"),
("La mia città \nMaa: Italy\nVuosi: 2014 \nSija: Finaali, 21", Pohja + Finaali, "https://www.youtube.com/watch?v=8W5ZlalAMV8&list=RD8W5ZlalAMV8&start_radio=1"),
("Start a Fire \nMaa: Azerbaijan\nVuosi: 2014 \nSija: Finaali, 22", Pohja + Finaali, "https://www.youtube.com/watch?v=5mPUMPcFQAY&list=RD5mPUMPcFQAY&start_radio=1"),
("Coming Home \nMaa: Malta\nVuosi: 2014 \nSija: Finaali, 23", Pohja + Finaali, "https://www.youtube.com/watch?v=E_hT08vzHt8&list=RDE_hT08vzHt8&start_radio=1"),
("Maybe \nMaa: San Marino\nVuosi: 2014 \nSija: Finaali, 24", Pohja + Finaali, "https://www.youtube.com/watch?v=_eZNTBJ-Hyc&list=RD_eZNTBJ-Hyc&start_radio=1"),
("Round and Round \nMaa: Slovenia\nVuosi: 2014 \nSija: Finaali, 25", Pohja + Finaali, "https://www.youtube.com/watch?v=CiwM1sY3u0s&list=RDCiwM1sY3u0s&start_radio=1"),
("Moustache \nMaa: France\nVuosi: 2014 \nSija: Finaali, 26", Pohja + Finaali, "https://www.youtube.com/watch?v=vjkqciwP034&list=RDvjkqciwP034&start_radio=1"),
("O mie \nMaa: Moldova\nVuosi: 2013 \nSija: Finaali, 11", Pohja + Finaali, "https://www.youtube.com/watch?v=xckgLUv73Jc&list=RDxckgLUv73Jc&start_radio=1"),
("Love Kills \nMaa: Belgium\nVuosi: 2013 \nSija: Finaali, 12", Pohja + Finaali, "https://www.youtube.com/watch?v=dCl7OUFNSCA&list=RDdCl7OUFNSCA&start_radio=1"),
("It's My Life \nMaa: Romania\nVuosi: 2013 \nSija: Finaali, 13", Pohja + Finaali, "https://www.youtube.com/watch?v=OV3xp5ZXSYA&list=RDOV3xp5ZXSYA&start_radio=1"),
("You \nMaa: Sweden\nVuosi: 2013 \nSija: Finaali, 14", Pohja + Finaali, "https://www.youtube.com/watch?v=vtjdTPnCcu0&list=RDvtjdTPnCcu0&start_radio=1"),
("Waterfall \nMaa: Georgia\nVuosi: 2013 \nSija: Finaali, 15", Pohja + Finaali, "https://www.youtube.com/watch?v=-n3mwx0vQDE&list=RD-n3mwx0vQDE&start_radio=1"),
("Solayoh \nMaa: Belarus\nVuosi: 2013 \nSija: Finaali, 16", Pohja + Finaali, "https://www.youtube.com/watch?v=XKewBfUE2Mg&list=RDXKewBfUE2Mg&start_radio=1"),
("Ég á líf \nMaa: Iceland\nVuosi: 2013 \nSija: Finaali, 17", Pohja + Finaali, "https://www.youtube.com/watch?v=GzE88IYzXLI&list=RDGzE88IYzXLI&start_radio=1"),
("Lonely Planet \nMaa: Armenia\nVuosi: 2013 \nSija: Finaali, 18", Pohja + Finaali, "https://www.youtube.com/watch?v=UGOSZ7Uufno&list=RDUGOSZ7Uufno&start_radio=1"),
("Believe in Me \nMaa: United Kingdom\nVuosi: 2013 \nSija: Finaali, 19", Pohja + Finaali, "https://www.youtube.com/watch?v=-agn-ERgTXA&list=RD-agn-ERgTXA&start_radio=1"),
("Et uus saaks alguse \nMaa: Estonia\nVuosi: 2013 \nSija: Finaali, 20", Pohja + Finaali, "https://www.youtube.com/watch?v=Ooo6GvZNLhI&list=RDOoo6GvZNLhI&start_radio=1"),
("Glorious \nMaa: Germany\nVuosi: 2013 \nSija: Finaali, 21", Pohja + Finaali, "https://www.youtube.com/watch?v=3HYTd7WDCPg&list=RD3HYTd7WDCPg&start_radio=1"),
("Something \nMaa: Lithuania\nVuosi: 2013 \nSija: Finaali, 22", Pohja + Finaali, "https://www.youtube.com/watch?v=0VLhnzk_dAs&list=RD0VLhnzk_dAs&start_radio=1"),
("L'Enfer et moi \nMaa: France\nVuosi: 2013 \nSija: Finaali, 23", Pohja + Finaali, "https://www.youtube.com/watch?v=hQwiQj5Dyj8&list=RDhQwiQj5Dyj8&start_radio=1"),
("Marry Me \nMaa: Finland\nVuosi: 2013 \nSija: Finaali, 24", Pohja + Finaali, "https://www.youtube.com/watch?v=dlBXOveVh7c&list=RDdlBXOveVh7c&start_radio=1"),
("Contigo hasta el final \nMaa: Spain\nVuosi: 2013 \nSija: Finaali, 25", Pohja + Finaali, "https://www.youtube.com/watch?v=5o_DnM_ANF8&list=RD5o_DnM_ANF8&start_radio=1"),
("Only Love Survives \nMaa: Ireland\nVuosi: 2013 \nSija: Finaali, 26", Pohja + Finaali, "https://www.youtube.com/watch?v=4tgtyl_5x5Y&list=RD4tgtyl_5x5Y&start_radio=1"),
("Lăutar \nMaa: Moldova\nVuosi: 2012 \nSija: Finaali, 11", Pohja + Finaali, "https://www.youtube.com/watch?v=vIy0EtEeLEw&list=RDvIy0EtEeLEw&start_radio=1"),
("Zaleilah \nMaa: Romania\nVuosi: 2012 \nSija: Finaali, 12", Pohja + Finaali, "https://www.youtube.com/watch?v=K3ruy639kTQ&list=RDK3ruy639kTQ&start_radio=1"),
("Crno i belo \nMaa: N.Macedonia\nVuosi: 2012 \nSija: Finaali, 13", Pohja + Finaali, "https://www.youtube.com/watch?v=MSuCdNEy9w0&list=RDMSuCdNEy9w0&start_radio=1"),
("Love Is Blind \nMaa: Lithuania\nVuosi: 2012 \nSija: Finaali, 14", Pohja + Finaali, "https://www.youtube.com/watch?v=x2vNoZnJxgY&list=RDx2vNoZnJxgY&start_radio=1"),
("Be My Guest \nMaa: Ukraine\nVuosi: 2012 \nSija: Finaali, 15", Pohja + Finaali, "https://www.youtube.com/watch?v=sLsTn_li5d8&list=RDsLsTn_li5d8&start_radio=1"),
("La La Love \nMaa: Cyprus\nVuosi: 2012 \nSija: Finaali, 16", Pohja + Finaali, "https://www.youtube.com/watch?v=ex133UhxB64&list=RDex133UhxB64&start_radio=1"),
("Aphrodisiac \nMaa: Greece\nVuosi: 2012 \nSija: Finaali, 17", Pohja + Finaali, "https://www.youtube.com/watch?v=NreIi8ma_PY&list=RDNreIi8ma_PY&start_radio=1"),
("Korake ti znam \nMaa: Bosnia & Herz.\nVuosi: 2012 \nSija: Finaali, 18", Pohja + Finaali, "https://www.youtube.com/watch?v=81hIbZNoFU8&list=RD81hIbZNoFU8&start_radio=1"),
("Waterline \nMaa: Ireland\nVuosi: 2012 \nSija: Finaali, 19", Pohja + Finaali, "https://www.youtube.com/watch?v=O_9QaVC-NKw&list=RDO_9QaVC-NKw&start_radio=1"),
("Never Forget \nMaa: Iceland\nVuosi: 2012 \nSija: Finaali, 20", Pohja + Finaali, "https://www.youtube.com/watch?v=zRqmHRbJvTo&list=RDzRqmHRbJvTo&start_radio=1"),
("This Is the Night \nMaa: Malta\nVuosi: 2012 \nSija: Finaali, 21", Pohja + Finaali, "https://www.youtube.com/watch?v=EgaX5QuMGR8&list=RDEgaX5QuMGR8&start_radio=1"),
("Echo (You and I) \nMaa: France\nVuosi: 2012 \nSija: Finaali, 22", Pohja + Finaali, "https://www.youtube.com/watch?v=0DZ7DbdeOeE&list=RD0DZ7DbdeOeE&start_radio=1"),
("Should've Known Better \nMaa: Denmark\nVuosi: 2012 \nSija: Finaali, 23", Pohja + Finaali, "https://www.youtube.com/watch?v=U5X2r_t-KBk&list=RDU5X2r_t-KBk&start_radio=1"),
("Sound of Our Hearts \nMaa: Hungary\nVuosi: 2012 \nSija: Finaali, 24", Pohja + Finaali, "https://www.youtube.com/watch?v=vCAlNahM8HY&list=RDvCAlNahM8HY&start_radio=1"),
("Love Will Set You Free \nMaa: United Kingdom\nVuosi: 2012 \nSija: Finaali, 25", Pohja + Finaali, "https://www.youtube.com/watch?v=rXw4Q5jbNqQ&list=RDrXw4Q5jbNqQ&start_radio=1"),
("Stay \nMaa: Norway\nVuosi: 2012 \nSija: Finaali, 26", Pohja + Finaali, "https://www.youtube.com/watch?v=-ZaxIY1VAbM&list=RD-ZaxIY1VAbM&start_radio=1"),
("I Can \nMaa: United Kingdom\nVuosi: 2011 \nSija: Finaali, 11", Pohja + Finaali, "https://www.youtube.com/watch?v=9mUKrCGshog&list=RD9mUKrCGshog&start_radio=1"),
("So Lucky \nMaa: Moldova\nVuosi: 2011 \nSija: Finaali, 12", Pohja + Finaali, "https://www.youtube.com/watch?v=nHAY_OVN_gY&list=RDnHAY_OVN_gY&start_radio=1"),
("No One \nMaa: Slovenia\nVuosi: 2011 \nSija: Finaali, 13", Pohja + Finaali, "https://www.youtube.com/watch?v=5vqjb2OYnYs&list=RD5vqjb2OYnYs&start_radio=1"),
("Čaroban \nMaa: Serbia\nVuosi: 2011 \nSija: Finaali, 14", Pohja + Finaali, "https://www.youtube.com/watch?v=-CWvXKxjCs8&list=RD-CWvXKxjCs8&start_radio=1"),
("Sognu \nMaa: France\nVuosi: 2011 \nSija: Finaali, 15", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=OTiBNPT-x_Y&list=RDOTiBNPT-x_Y&start_radio=1"),
("Get You \nMaa: Russia\nVuosi: 2011 \nSija: Finaali, 16", Pohja + Finaali, "https://www.youtube.com/watch?v=C-3ohaRN3MM&list=RDC-3ohaRN3MM&start_radio=1"),
("Change \nMaa: Romania\nVuosi: 2011 \nSija: Finaali, 17", Pohja + Finaali, "https://www.youtube.com/watch?v=2a1Q_hpGLbs&list=RD2a1Q_hpGLbs&start_radio=1"),
("The Secret Is Love \nMaa: Austria\nVuosi: 2011 \nSija: Finaali, 18", Pohja + Finaali, "https://www.youtube.com/watch?v=UsBC5AB1tFo&list=RDUsBC5AB1tFo&start_radio=1"),
("C'est ma vie \nMaa: Lithuania\nVuosi: 2011 \nSija: Finaali, 19", Pohja + Finaali, "https://www.youtube.com/watch?v=D4Tvc9S_1BU&list=RDD4Tvc9S_1BU&start_radio=1"),
("Coming Home \nMaa: Iceland\nVuosi: 2011 \nSija: Finaali, 20", Pohja + Finaali, "https://www.youtube.com/watch?v=apc_qJf3nws&list=RDapc_qJf3nws&start_radio=1"),
("Da Da Dam \nMaa: Finland\nVuosi: 2011 \nSija: Finaali, 21", Pohja + Finaali, "https://www.youtube.com/watch?v=1Fj9of4IzFU&list=RD1Fj9of4IzFU&start_radio=1"),
("What About My Dreams? \nMaa: Hungary\nVuosi: 2011 \nSija: Finaali, 22", Pohja + Finaali, "https://www.youtube.com/watch?v=kwH7Pw25kNk&list=RDkwH7Pw25kNk&start_radio=1"),
("Que me quiten lo bailao \nMaa: Spain\nVuosi: 2011 \nSija: Finaali, 23", Pohja + Finaali, "https://www.youtube.com/watch?v=GSOEmM0h-aE&list=RDGSOEmM0h-aE&start_radio=1"),
("Rockefeller Street \nMaa: Estonia\nVuosi: 2011 \nSija: Finaali, 24", Pohja + Finaali, "https://www.youtube.com/watch?v=vOIXQskfy6o&list=RDvOIXQskfy6o&start_radio=1"),
("In Love for a While \nMaa: Switzerland\nVuosi: 2011 \nSija: Finaali, 25", Pohja + Finaali, "https://www.youtube.com/watch?v=M03Nx6gHd90&list=RDM03Nx6gHd90&start_radio=1"),
("Lost and Forgotten \nMaa: Russia\nVuosi: 2010 \nSija: Finaali, 11", Pohja + Finaali, "https://www.youtube.com/watch?v=nFEwKjpDD2c&list=RDnFEwKjpDD2c&start_radio=1"),
("Allez Ola Olé \nMaa: France\nVuosi: 2010 \nSija: Finaali, 12", Pohja + Finaali, "https://www.youtube.com/watch?v=-NlvQ6Ln9fc&list=RD-NlvQ6Ln9fc&start_radio=1"),
("Ovo je Balkan \nMaa: Serbia\nVuosi: 2010 \nSija: Finaali, 13", Pohja + Finaali, "https://www.youtube.com/watch?v=4pVEII2pmso&list=RD4pVEII2pmso&start_radio=1"),
("Milim \nMaa: Israel\nVuosi: 2010 \nSija: Finaali, 14", Pohja + Finaali, "https://www.youtube.com/watch?v=Tj0qaNnLk9M&list=RDTj0qaNnLk9M&start_radio=1"),
("Algo pequeñito \nMaa: Spain\nVuosi: 2010 \nSija: Finaali, 15", Pohja + Finaali, "https://www.youtube.com/watch?v=6gltZu8lsFc&list=RD6gltZu8lsFc&start_radio=1"),
("It's All About You \nMaa: ALbania\nVuosi: 2010 \nSija: Finaali, 16", Pohja + Finaali, "https://www.youtube.com/watch?v=idE_32NUJbo&list=RDidE_32NUJbo&start_radio=1"),
("Thunder and Lightning \nMaa: Bosnia & Herz.\nVuosi: 2010 \nSija: Finaali, 17", Pohja + Finaali, "https://www.youtube.com/watch?v=IPBo9vaN9Vc&list=RDIPBo9vaN9Vc&start_radio=1"),
("Há dias assim \nMaa: Portugal\nVuosi: 2010 \nSija: Finaali, 18", Pohja + Finaali, "https://www.youtube.com/watch?v=TvmnvtL_DcQ&list=RDTvmnvtL_DcQ&start_radio=1"),
("Je ne sais quoi \nMaa: Iceland\nVuosi: 2010 \nSija: Finaali, 19", Pohja + Finaali, "https://www.youtube.com/watch?v=qXLqw4UpJ1w&list=RDqXLqw4UpJ1w&start_radio=1"),
("My Heart Is Yours \nMaa: Norway\nVuosi: 2010 \nSija: Finaali, 20", Pohja + Finaali, "https://www.youtube.com/watch?v=9w527tADNpc&list=RD9w527tADNpc&start_radio=1"),
("Life Looks Better in Spring \nMaa: Cyprus\nVuosi: 2010 \nSija: Finaali, 21", Pohja + Finaali, "https://www.youtube.com/watch?v=ZGNtoR2hom4&list=RDZGNtoR2hom4&start_radio=1"),
("Run Away \nMaa: Moldova\nVuosi: 2010 \nSija: Finaali, 22", Pohja + Finaali + Suosikki, "https://www.youtube.com/watch?v=pHXDMe6QV-U&list=RDpHXDMe6QV-U&start_radio=1"),
("It's for You \nMaa: Ireland\nVuosi: 2010 \nSija: Finaali, 23", Pohja + Finaali, "https://www.youtube.com/watch?v=6SHg8gS-02Q&list=RD6SHg8gS-02Q&start_radio=1"),
("Butterflies \nMaa: Belarus\nVuosi: 2010 \nSija: Finaali, 24", Pohja + Finaali, "https://www.youtube.com/watch?v=MvK2KU2zfzA&list=RDMvK2KU2zfzA&start_radio=1"),
("That Sounds Good to Me \nMaa: United Kingdom\nVuosi: 2010 \nSija: Finaali, 25", Pohja + Finaali, "https://www.youtube.com/watch?v=BLiL-tRxhkE&list=RDBLiL-tRxhkE&start_radio=1"),

("Freedom \nMaa: Georgia\nVuosi: 2025 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Shh \nMaa: Cyprus\nVuosi: 2025 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Kiss Kiss Goodbye \nMaa: Czechia\nVuosi: 2025 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Poison Cake \nMaa: Croatia\nVuosi: 2025 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Run With U \nMaa: Azerbaijan\nVuosi: 2025 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Mila \nMaa: Serbia\nVuosi: 2025 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Milkshake man \nMaa: Australia\nVuosi: 2025 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Laika Party \nMaa: Ireland\nVuosi: 2025 \nSija: Ei päässyt finaaliin", Pohja, ""),
("How Much Time Do We Have Left \nMaa: Slovenia\nVuosi: 2025 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Strobe Lights \nMaa: Belgium\nVuosi: 2025 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Dobrodosli \nMaa: Montenegro\nVuosi: 2025 \nSija: Ei päässyt finaaliin", Pohja, ""),
("One Milkali (One Blood) \nMaa: Australia\nVuosi: 2024 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Pedestal \nMaa: Czechia\nVuosi: 2024 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Sand \nMaa: Poland\nVuosi: 2024 \nSija: Ei päässyt finaaliin", Pohja, ""),
("The Tower \nMaa: Denmark\nVuosi: 2024 \nSija: Ei päässyt finaaliin", Pohja, ""),
("In the Middle \nMaa: Moldova\nVuosi: 2024 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Before the Party's Over \nMaa: Belgium\nVuosi: 2024 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("11:11 \nMaa: San Marino\nVuosi: 2024 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Özünlə apar \nMaa: Albania\nVuosi: 2024 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Titan \nMaa: Malta\nVuosi: 2024 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Scared of Heights \nMaa: Azerbaijan\nVuosi: 2024 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Loop \nMaa: Iceland\nVuosi: 2024 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Power \nMaa: Iceland\nVuosi: 2023 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Aijā \nMaa: Latvia\nVuosi: 2023 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Echo \nMaa: Echo\nVuosi: 2023 \nSija: Ei päässyt finaaliin", Pohja, ""),
("We Are One \nMaa: Greece\nVuosi: 2023 \nSija: Ei päässyt finaaliin", Pohja, ""),
("What They Say \nMaa: Ireland\nVuosi: 2023 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Burning Daylight \nMaa: Netherlands\nVuosi: 2023 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Breaking My Heart \nMaa: Denmark\nVuosi: 2023 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Tell Me More \nMaa: Azerbaijan\nVuosi: 2023 \nSija: Ei päässyt finaaliin", Pohja, ""),
("D.G.T. (Off and On) \nMaa: Romania\nVuosi: 2023 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Dance (Our Own Party) \nMaa: Malta\nVuosi: 2023 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Like an Animal \nMaa: San Marino\nVuosi: 2023 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Circles \nMaa: N.Macedonia\nVuosi: 2022 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Guilty Pleasure \nMaa: Croatia\nVuosi: 2022 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Ela \nMaa: Cyprus\nVuosi: 2022 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Sekret \nMaa: Albania\nVuosi: 2022 \nSija: Ei päässyt finaaliin", Pohja, ""),
("I.M \nMaa: Israel\nVuosi: 2022 \nSija: Ei päässyt finaaliin", Pohja, ""),
("The Show \nMaa: Denmark\nVuosi: 2022 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Eat Your Salad \nMaa: Latvia\nVuosi: 2022 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Stripper \nMaa: San Marino\nVuosi: 2022 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("That's Rich \nMaa: Ireland\nVuosi: 2022 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Halo \nMaa: Austria\nVuosi: 2022 \nSija: Ei päässyt finaaliin", Pohja, ""),
("I Am What I Am \nMaa: Malta\nVuosi: 2022 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Intention \nMaa: Bulgaria\nVuosi: 2022 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Breathe \nMaa: Montenegro\nVuosi: 2022 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Disco \nMaa: Slovenia\nVuosi: 2022 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Lock Me In \nMaa: Georgia\nVuosi: 2022 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Tick-Tock \nMaa: Croatia\nVuosi: 2021 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Øve os på hinanden \nMaa: Denmark\nVuosi: 2021 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Amnesia \nMaa: Romania\nVuosi: 2021 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Amen \nMaa: Austria\nVuosi: 2021 \nSija: Ei päässyt finaaliin", Pohja, ""),
("The Lucky One \nMaa: Estonia\nVuosi: 2021 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Amen \nMaa: Slovenia\nVuosi: 2021 \nSija: Ei päässyt finaaliin", Pohja, ""),
("The Ride \nMaa: Poland\nVuosi: 2021 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Technicolour \nMaa: Australia\nVuosi: 2021 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Here I Stand \nMaa: N.Macedonia\nVuosi: 2021 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Omaga \nMaa: Czechia\nVuosi: 2021 \nSija: Ei päässyt finaaliin", Pohja, ""),
("You \nMaa: Georgia\nVuosi: 2021 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Maps \nMaa: Ireland\nVuosi: 2021 \nSija: Ei päässyt finaaliin", Pohja, ""),
("The Moon Is Rising \nMaa: Latvia\nVuosi: 2021 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Fall from the Sky \nMaa: Albania\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Chains on You \nMaa: Armenia\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Don't Break Me \nMaa: Australia\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Alive \nMaa: Austria\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Cleopatra \nMaa: Azerbaijan\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Da vidna \nMaa: Belarus\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Release Me \nMaa: Belgium\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Tears Getting Sober \nMaa: Bulgaria\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Divlji vjetre \nMaa: Croatia\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Running \nMaa: Cyprus\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Kemama \nMaa: Czechia\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Yes \nMaa: Denmark\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("What Love Is \nMaa: Estonia\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Looking Back \nMaa: Finland\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Mon alliée (The Best in Me) \nMaa: France\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Take Me as I Am \nMaa: Georgia\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Violent Thing \nMaa: Germany\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Supergirl \nMaa: Greece\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Think About Things \nMaa: Iceland\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Story of My Life \nMaa: Ireland\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Feker Libi \nMaa: Israel\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Fai rumore \nMaa: Italy\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Still Breathing \nMaa: Latvia\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("On Fire \nMaa: Lithuania\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("All of My Love \nMaa: Malta\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Prison \nMaa: Moldova\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Grow \nMaa: Netherlands\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("You \nMaa: North Macedonia\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Attention \nMaa: Norway\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Empires \nMaa: Poland\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Medo de sentir \nMaa: Portugal\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Alcohol You \nMaa: Romania\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Uno \nMaa: Russia\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Freaky! \nMaa: San Marino\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Hasta la vista \nMaa: Serbia\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Voda \nMaa: Slovenia\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Universo \nMaa: Spain\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Move \nMaa: Sweden\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Répondez-moi \nMaa: Switzerland\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Solovey \nMaa: Ukraine\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("My Last Breath \nMaa: United Kingdom\nVuosi: 2020 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Heaven \nMaa: Montenegro\nVuosi: 2019 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Look Away \nMaa: Finland\nVuosi: 2019 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Fire of Love (Pali się) \nMaa: Poland\nVuosi: 2019 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Az én apám \nMaa: Hungary\nVuosi: 2019 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Wake Up \nMaa: Belgium\nVuosi: 2019 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Keep On Going \nMaa: Georgia\nVuosi: 2019 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Telemóveis \nMaa: Portugal\nVuosi: 2019 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Walking Out \nMaa: Armenia\nVuosi: 2019 \nSija: Ei päässyt finaaliin", Pohja, ""),
("22 \nMaa: Ireland\nVuosi: 2019 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Stay \nMaa: Moldova\nVuosi: 2019 \nSija: Ei päässyt finaaliin", Pohja, ""),
("That Night \nMaa: Latvia\nVuosi: 2019 \nSija: Ei päässyt finaaliin", Pohja, ""),
("On a Sunday \nMaa: Romania\nVuosi: 2019 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Limits \nMaa: Austria\nVuosi: 2019 \nSija: Ei päässyt finaaliin", Pohja, ""),
("The Dream \nMaa: Croatia\nVuosi: 2019 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Run with the Lions \nMaa: Lithuania\nVuosi: 2019 \nSija: Ei päässyt finaaliin", Pohja, ""),
("X My Heart \nMaa: Azerbaijan\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Our Choice \nMaa: Iceland\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja, ""),
("A Matter of Time \nMaa: Belgium\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Forever \nMaa: Belarus\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Lost and Found \nMaa: N.Macedonia\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Crazy \nMaa: Croatia\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Oniro mou \nMaa: Greece\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Qami \nMaa: Armenia\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Stones \nMaa: Switzerland\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Goodbye \nMaa: Romania\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Who We Are \nMaa: San Marino\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja, ""),
("I Won't Break \nMaa: Russia\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("For You \nMaa: Georgia\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Light Me Up \nMaa: Poland\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Taboo \nMaa: Malta\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Funny Girl \nMaa: Latvia\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Inje \nMaa: Montenegro\nVuosi: 2018 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Keep the Faith \nMaa: Georgia\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("World \nMaa: Albania\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Space \nMaa: Montenegro\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Blackbird \nMaa: Finland\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Paper \nMaa: Iceland\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("My Turn \nMaa: Czechia\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("On My Way \nMaa: Slovenia\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Line \nMaa: Latvia\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("In Too Deep \nMaa: Serbia\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Dance Alone \nMaa: N.Macedonia\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Breathlessly \nMaa: Malta\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Dying to Try \nMaa: Ireland\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Spirit of the Night \nMaa: San Marino\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Apollo \nMaa: Switzerland\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Rain of Revolution \nMaa: Lithuania\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Verona \nMaa: Estonia\nVuosi: 2017 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Sing It Away \nMaa: Finland\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Utopian Land \nMaa: Greece\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Falling Stars \nMaa: Moldova\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("I Didn't Know \nMaa: San Marino\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Play \nMaa: Estonia\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("The Real Thing \nMaa: Montenegro\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Hear Them Calling \nMaa: Iceland\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Ljubav je \nMaa: Bosnia & Herz.\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("The Last of Our Kind \nMaa: Switzerland\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Help You Fly \nMaa: Belarus\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Sunlight \nMaa: Ireland\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Dona \nMaa: N.Macedonia\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Blue and Red \nMaa: Slovenia\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Soldiers of Love \nMaa: Denmark\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Icebreaker \nMaa: Norway\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Fairytale \nMaa: Albania\nVuosi: 2016 \nSija: Ei päässyt finaaliin", Pohja, ""),
("I Want Your Love \nMaa: Moldova\nVuosi: 2015 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Walk Along \nMaa: Netherlands\nVuosi: 2015 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Aina mun pitää \nMaa: Finland\nVuosi: 2015 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Autumn Leaves \nMaa: N.Macedonia\nVuosi: 2015 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Time \nMaa: Belarus\nVuosi: 2015 \nSija: Ei päässyt finaaliin", Pohja, ""),
("The Way You Are \nMaa: Denmark\nVuosi: 2015 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Playing with Numbers \nMaa: Ireland\nVuosi: 2015 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Chain of Lights \nMaa: San Marino\nVuosi: 2015 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Warrior\nMaa: Malta\nVuosi: 2015 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Há um mar que nos separa \nMaa: Portugal\nVuosi: 2015 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Hope Never Dies \nMaa: Czechia\nVuosi: 2015 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Unbroken \nMaa: Iceland\nVuosi: 2015 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Time to Shine \nMaa: Switzerland\nVuosi: 2015 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Cake to Bake \nMaa: Latvia\nVuosi: 2014 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Amazing \nMaa: Estonia\nVuosi: 2014 \nSija: Ei päässyt finaaliin", Pohja, ""),
("One Night's Anger \nMaa: Albania\nVuosi: 2014 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Mother \nMaa: Belgium\nVuosi: 2014 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Wild Soul \nMaa: Moldova\nVuosi: 2014 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Quero ser tua \nMaa: Portugal\nVuosi: 2014 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Same Heart \nMaa: Israel\nVuosi: 2014 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Three Minutes to Earth \nMaa: Georgia\nVuosi: 2014 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Attention \nMaa: Lithuania\nVuosi: 2014 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Heartbeat \nMaa: Ireland\nVuosi: 2014 \nSija: Ei päässyt finaaliin", Pohja, ""),
("To the Sky \nMaa: N.Macedonia\nVuosi: 2014 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Shine \nMaa: Austria\nVuosi: 2013 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Straight into Love \nMaa: Slovenia\nVuosi: 2013 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Mižerja \nMaa: Croatia\nVuosi: 2013 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Igranka \nMaa: Montenegro\nVuosi: 2013 \nSija: Ei päässyt finaaliin", Pohja, ""),
("An me thimasai \nMaa: Cyprus\nVuosi: 2013 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Ljubav je svuda \nMaa: Serbia\nVuosi: 2013 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Here We Go \nMaa: Latvia\nVuosi: 2013 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Crisalide (Vola) \nMaa: San Marino\nVuosi: 2013 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Pred da se razdeni \nMaa: N.Macedonia\nVuosi: 2013 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Samo shampioni \nMaa: Bulgaria\nVuosi: 2013 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Rak Bishvilo \nMaa: Israel\nVuosi: 2013 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Identitet \nMaa: Albania\nVuosi: 2013 \nSija: Ei päässyt finaaliin", Pohja, ""),
("You and Me \nMaa: Switzerland\nVuosi: 2013 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Euro Neuro \nMaa: Montenegro\nVuosi: 2012 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Beautiful Song \nMaa: Latvia\nVuosi: 2012 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Unbreakable \nMaa: Switzerland\nVuosi: 2012 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Would You? \nMaa: Belgium\nVuosi: 2012 \nSija: Ei päässyt finaaliin", Pohja, ""),
("När jag blundar \nMaa: Finland\nVuosi: 2012 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Time \nMaa: Israel\nVuosi: 2012 \nSija: Ei päässyt finaaliin", Pohja, ""),
("The Social Network Song (Oh Oh – Uh – Oh Oh) \nMaa: San Marino\nVuosi: 2012 \nSija: Ei päässyt finaaliin",Pohja, ""),
("Woki mit deim Popo \nMaa: Austria\nVuosi: 2012 \nSija: Ei päässyt finaaliin", Pohja, ""),
("You and Me \nMaa: Netherlands\nVuosi: 2012 \nSija: Ei päässyt finaaliin", Pohja, ""),
("We Are the Heroes \nMaa: Belarus\nVuosi: 2012 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Vida minha \nMaa: Portugal\nVuosi: 2012 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Love Unlimited \nMaa: Bulgaria\nVuosi: 2012 \nSija: Ei päässyt finaaliin", Pohja + Suosikki, ""),
("Verjamem \nMaa: Slovenia\nVuosi: 2012 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Nebo \nMaa: Croatia\nVuosi: 2012 \nSija: Ei päässyt finaaliin", Pohja, ""),
("I'm a Joker \nMaa: Georgia\nVuosi: 2012 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Don't Close Your Eyes \nMaa: Slovakia\nVuosi: 2012 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Jestem \nMaa: Poland\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Haba Haba \nMaa: Norway\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Feel the Passion \nMaa: Albania\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Boom Boom \nMaa: Armenia\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Live It Up \nMaa: Turkey\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("One Life \nMaa: Malta\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Stand By \nMaa: San Marino\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Celebrate \nMaa: Croatia\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("A luta é alegria \nMaa: Portugal\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Never Alone \nMaa: Netherlands\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("With Love Baby \nMaa: Belgium\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("I'm Still Alive \nMaa: Slovakia\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("San aggelos s'agapisa \nMaa: Cyprus\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Na inat \nMaa: Bulgaria\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Rusinka \nMaa: N.Macedonia\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Ding Dong \nMaa: Israel\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("I Love Belarus \nMaa: Belarus\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Angel in Disguise \nMaa: Latvia\nVuosi: 2011 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Siren \nMaa: Estonia\nVuosi: 2010 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Horehronie \nMaa: Slovakia\nVuosi: 2010 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Työlki ellää \nMaa: Finland\nVuosi: 2010 \nSija: Ei päässyt finaaliin", Pohja, ""),
("What For? \nMaa: Latvia\nVuosi: 2010 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Legenda \nMaa: Poland\nVuosi: 2010 \nSija: Ei päässyt finaaliin", Pohja, ""),
("My Dream \nMaa: Malta\nVuosi: 2010 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Jas ja imam silata \nMaa: N.Macedonia\nVuosi: 2010 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Eastern European Funk \nMaa: Lithuania\nVuosi: 2010 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Il pleut de l'or \nMaa: Switzerland\nVuosi: 2010 \nSija: Ei päässyt finaaliin", Pohja, ""),
("This Is My Life \nMaa: Sweden\nVuosi: 2010 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Ik ben verliefd (Sha-la-lie) \nMaa: Netherlands\nVuosi: 2010 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Narodnozabavni rock \nMaa: Slovenia\nVuosi: 2010 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Angel si ti \nMaa: Bulgaria\nVuosi: 2010 \nSija: Ei päässyt finaaliin", Pohja, ""),
("Lako je sve \nMaa: Croatia\nVuosi: 2010 \nSija: Ei päässyt finaaliin", Pohja, ""),

#(" \nMaa: \nVuosi: 2026, extra", Extra, ""),


(" Ēnā\nMaa: Latvia\nVuosi: 2026, extra", Extra, ""),
(" Too Epic To Be True\nMaa: Estonia\nVuosi: 2026, extra", Extra, ""),
(" Før vi går hjem\nMaa: Denmark\nVuosi: 2026, extra", Extra, ""),
("Jalla \nMaa: Cyprus\nVuosi: 2026, extra", Extra, ""),
("Ridnym \nMaa: Ukraine\nVuosi: 2026, extra", Extra, ""),
("Mother Nature \nMaa: Luxembourg\nVuosi: 2026, extra", Extra, ""),
("Bella \nMaa: Malta\nVuosi: 2026, extra", Extra, ""),
("Viva Moldova! \nMaa: Moldova\nVuosi: 2026, extra", Extra, ""),
("Nova Zora \nMaa: Montenegro\nVuosi: 2026, extra", Extra, ""),
("Nan \nMaa: Albania\nVuosi: 2026, extra", Extra, ""),

("Tristesa \nMaa: Portugal\nVuosi: 2025, extra", Extra, ""),
("My AI \nMaa: Norway\nVuosi: 2024, extra", Extra, ""),
("Kuori mua \nMaa: Finland\nVuosi: 2024, extra", Extra, ""),
("#askana \nMaa: Finland\nVuosi: 2024, extra", Extra, ""),
("My friend \nMaa: Estonia\nVuosi: 2024, extra", Extra, ""),
("Babaroga \nMaa: Croatia\nVuosi: 2024, extra", Extra, ""),
("Arcadia \nMaa: Spain\nVuosi: 2023, extra", Extra, ""),

]

# -------------------------------------------
# Routes
# -------------------------------------------

@app.route("/")
def index():
    return render_template("index.html")


from flask import redirect

@app.route("/generate")
def generate():
    weights = [song[1] for song in songs]
    selected = random.choices(songs, weights=weights, k=1)[0]

    description, weight, youtube_link = selected
    session["song"] = {"description": description, "youtube": youtube_link}

    return redirect("/reveal")



@app.route("/reveal")
def reveal():
    song = session.get("song")
    return render_template("reveal.html", song=song)


# -------------------------------------------
# Run the app
# -------------------------------------------

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)


